/*
 * File: app/view/user/UserListView.js
 *
 * This file was generated by Sencha Architect version 4.2.8.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.view.user.UserListView', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.user.userlistview',

    requires: [
        'ASTD.view.user.UserListViewModel',
        'ASTD.view.user.UserListViewController',
        'Ext.grid.column.Column',
        'Ext.view.Table',
        'Ext.toolbar.Paging',
        'Ext.form.FieldContainer',
        'Ext.form.field.ComboBox',
        'Ext.button.Button'
    ],

    controller: 'user.userlistview',
    viewModel: {
        type: 'user.userlistview'
    },
    reference: 'userList',
    cls: 'my-title',
    iconCls: 'x-fa fa-table',
    title: 'Пользователи',
    enableColumnHide: false,
    enableColumnMove: false,
    enableColumnResize: false,
    sortableColumns: false,

    bind: {
        store: '{userStore}'
    },
    columns: [
        {
            xtype: 'gridcolumn',
            flex: 1,
            dataIndex: 'prevId',
            text: 'Id'
        },
        {
            xtype: 'gridcolumn',
            flex: 1,
            dataIndex: 'name',
            text: 'Имя'
        },
        {
            xtype: 'gridcolumn',
            flex: 1,
            dataIndex: 'positionName',
            text: 'Должность'
        },
        {
            xtype: 'gridcolumn',
            flex: 1,
            dataIndex: 'organization',
            text: 'Организация'
        }
    ],
    viewConfig: {
        loadMask: false
    },
    dockedItems: [
        {
            xtype: 'pagingtoolbar',
            dock: 'bottom',
            displayInfo: true,
            bind: {
                store: '{userStore}'
            }
        },
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'fieldcontainer',
                    defaults: {
                        flex: 1
                    },
                    fieldLabel: 'Фильтры',
                    labelWidth: 70,
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'combobox',
                            reference: 'positionCombox',
                            margin: '0 5 0 0',
                            fieldLabel: 'Должность',
                            labelWidth: 70,
                            editable: false,
                            displayField: 'name',
                            forceSelection: true,
                            queryMode: 'local',
                            valueField: 'id',
                            bind: {
                                store: '{positionStore}'
                            },
                            listeners: {
                                change: 'onPositionChange'
                            }
                        },
                        {
                            xtype: 'combobox',
                            reference: 'catalogComboBox',
                            fieldLabel: 'Каталог',
                            labelWidth: 70,
                            editable: false,
                            displayField: 'name',
                            forceSelection: true,
                            queryMode: 'local',
                            valueField: 'id',
                            bind: {
                                store: '{catalogStore}'
                            },
                            listeners: {
                                change: 'onCatalogChange'
                            }
                        }
                    ]
                },
                {
                    xtype: 'button',
                    iconCls: 'x-fa fa-plus',
                    text: 'Создать',
                    listeners: {
                        click: 'onCreateBtnClick'
                    }
                },
                {
                    xtype: 'button',
                    iconCls: 'x-fa fa-edit',
                    text: 'Редактировать',
                    listeners: {
                        click: 'onEditBtnClick'
                    }
                },
                {
                    xtype: 'button',
                    iconCls: 'x-fa fa-minus',
                    text: 'Удалить',
                    listeners: {
                        click: 'onDeleteBtnClick'
                    }
                }
            ]
        }
    ],
    listeners: {
        itemdblclick: 'onUserItemDblClick'
    }

});