/*
 * File: app/view/user/UserListViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.view.user.UserListViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.user.userlistview',

    editBtnClick: function() {
        var win = new ASTD.view.user.UserFormView({
            viewModel: {
                data: {
                    currentUser: this.getView().getSelection()[0],
                    userList: this.getView()
                }
            }
        });

        win.show();
    },

    onCompleteDelete: function(record, operation, success) {
        Ext.Msg.hide();
        if(success){
            Ext.Msg.wait("Загрузка", "Загрузка списка");
            this.getView().getStore().reload();
        } else {
            record.dropped = false;
        }
        Ext.toast({
            title: 'Удаление',
            html: success ? 'Пользователь успешно удален' : 'Ошибка',
            align: 'tr',
            bodyPadding: 10
        });
    },

    onCreateBtnClick: function(button, e, eOpts) {
        var currentUser = Ext.create('ASTD.model.UserModel');
        currentUser.setId('');

        var win = new ASTD.view.user.UserFormView({
            viewModel: {
                data: {
                    currentUser: currentUser,
                    userList: this.getView(),
                    userViewModel: this.getViewModel()
                }
            }
        });

        win.show();
    },

    onEditBtnClick: function(button, e, eOpts) {
        if(!ASTD.Utils.isSelected(this.getView().getSelection()[0])){
            return false;
        }

        this.editBtnClick();
    },

    onDeleteBtnClick: function(button, e, eOpts) {
        if(!ASTD.Utils.isSelected(this.getView().getSelection()[0])){
            return false;
        }
        Ext.Msg.show({
            title:'Удалить?',
            message: 'Вы действительно хотите удалить?',
            buttons: Ext.Msg.YESNO,
            icon: Ext.Msg.QUESTION,
            scope: this,
            fn: function(btn) {
                if(btn === 'yes') {
                    var currentUser = this.getView().getSelection()[0];
                    Ext.Msg.wait('Удаление', 'Удаление...');
                    currentUser.dropped = true;
                    currentUser.save({
                        scope: this,
                        callback: this.onCompleteDelete
                    });
                }
            }
        });
    },

    onUserItemDblClick: function(dataview, record, item, index, e, eOpts) {
        this.editBtnClick();
    }

});
