/*
 * File: app/view/user/UserListView.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.view.user.UserListView', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.user.userlistview',

    requires: [
        'ASTD.view.user.UserListViewModel',
        'ASTD.view.user.UserListViewController',
        'Ext.grid.column.Column',
        'Ext.view.Table',
        'Ext.toolbar.Paging',
        'Ext.button.Button'
    ],

    controller: 'user.userlistview',
    viewModel: {
        type: 'user.userlistview'
    },
    reference: 'userList',
    cls: 'my-title',
    glyph: 'xf0ce@FontAwesome',
    title: 'Пользователи',
    enableColumnHide: false,
    enableColumnMove: false,
    enableColumnResize: false,
    sortableColumns: false,

    bind: {
        store: '{userStore}'
    },
    columns: [
        {
            xtype: 'gridcolumn',
            flex: 1,
            dataIndex: 'prevId',
            text: 'Id'
        },
        {
            xtype: 'gridcolumn',
            flex: 1,
            dataIndex: 'name',
            text: 'Имя'
        },
        {
            xtype: 'gridcolumn',
            flex: 1,
            dataIndex: 'positionName',
            text: 'Должность'
        },
        {
            xtype: 'gridcolumn',
            flex: 1,
            dataIndex: 'organization',
            text: 'Организация'
        }
    ],
    viewConfig: {
        loadMask: false
    },
    dockedItems: [
        {
            xtype: 'pagingtoolbar',
            dock: 'bottom',
            displayInfo: true,
            bind: {
                store: '{userStore}'
            }
        },
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'button',
                    glyph: 'xf067@FontAwesome',
                    text: 'Создать',
                    listeners: {
                        click: 'onCreateBtnClick'
                    }
                },
                {
                    xtype: 'button',
                    glyph: 'xf044@FontAwesome',
                    text: 'Редактировать',
                    listeners: {
                        click: 'onEditBtnClick'
                    }
                },
                {
                    xtype: 'button',
                    glyph: 'xf068@FontAwesome',
                    text: 'Удалить',
                    listeners: {
                        click: 'onDeleteBtnClick'
                    }
                }
            ]
        }
    ],
    listeners: {
        itemdblclick: 'onUserItemDblClick'
    }

});