/*
 * File: app/view/user/UserFormView.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.view.user.UserFormView', {
    extend: 'Ext.window.Window',
    alias: 'widget.user.userformview',

    requires: [
        'ASTD.view.user.UserFormViewModel',
        'ASTD.view.user.UserFormViewController',
        'Ext.form.Panel',
        'Ext.form.field.Date',
        'Ext.form.field.ComboBox',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    controller: 'user.userformview',
    viewModel: {
        type: 'user.userformview'
    },
    modal: true,
    width: 600,
    layout: 'fit',
    header: {
        glyph: 'xf044@FontAwesome'
    },
    title: 'Пользователь',

    items: [
        {
            xtype: 'form',
            reference: 'userForm',
            modelValidation: true,
            bodyPadding: 10,
            header: false,
            items: [
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Id',
                    allowBlank: false,
                    bind: {
                        value: '{currentUser.id}'
                    }
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'ФИО',
                    bind: {
                        value: '{currentUser.name}'
                    }
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Организация',
                    allowBlank: false,
                    bind: {
                        value: '{currentUser.organization}'
                    }
                },
                {
                    xtype: 'datefield',
                    anchor: '100%',
                    fieldLabel: 'Действует до',
                    bind: {
                        value: '{currentUser.expiredDate}'
                    }
                },
                {
                    xtype: 'combobox',
                    anchor: '100%',
                    fieldLabel: 'Каталог',
                    editable: false,
                    displayField: 'name',
                    forceSelection: true,
                    queryMode: 'local',
                    valueField: 'id',
                    bind: {
                        value: '{currentUser.rootCatalogId}',
                        store: '{catalogStore}'
                    }
                },
                {
                    xtype: 'combobox',
                    anchor: '100%',
                    fieldLabel: 'Должность',
                    allowBlank: false,
                    editable: false,
                    displayField: 'name',
                    forceSelection: true,
                    queryMode: 'local',
                    valueField: 'id',
                    bind: {
                        value: '{currentUser.positionId}',
                        store: '{positionStore}'
                    }
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'bottom',
            ui: 'footer',
            layout: {
                type: 'hbox',
                pack: 'end'
            },
            items: [
                {
                    xtype: 'button',
                    glyph: 'xf0c7@FontAwesome',
                    text: 'Сохранить',
                    listeners: {
                        click: 'onSaveClick'
                    }
                },
                {
                    xtype: 'button',
                    glyph: 'xf057@FontAwesome',
                    text: 'Отменить',
                    listeners: {
                        click: 'onCancelClick'
                    }
                }
            ]
        }
    ]

});