/*
 * File: app/view/main/MainMoreRejectedListViewModel.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.view.main.MainMoreRejectedListViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.main.mainmorerejectedlistview',

    requires: [
        'Ext.data.Store',
        'Ext.app.bind.Formula'
    ],

    stores: {
        moreRejectedStore: {
            remoteFilter: true,
            autoLoad: true,
            model: 'ASTD.model.MoreRejectedModel'
        }
    },
    formulas: {
        isNoteHidden: function(get) {
            var user = this.get('current.user');
            if(!user) {
                return true;
            }
            return user.get('positionId') !== 5;
        }
    }

});