/*
 * File: app/view/main/MainViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.view.main.MainViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.main.mainview',

    onClickDocList: function(view, record) {
        if(view){
           this.getView().remove(view);
        }

        var fileList = new ASTD.view.file.FileListView({
            region: 'center',
            viewModel: {
                data: {
                    docId: record.getId()
                }
            },
            listeners: {
                clickFileHistoryBtn: 'onClickFileHistoryBtn'
            }
        });
        this.getView().add(fileList);
        this.getViewModel().notify();
        Ext.Msg.wait("Загрузка", "Загрузка списка");
        //fileList.getStore().load({params:{docId: record.getId(), branchType: record.get('branchType')}});
        fileList.getViewModel().getStore('fileStore').getProxy().setExtraParams({
            docId: record.getId(),
            branchType: this.getViewModel().get("current.branchType")
        });
        fileList.getViewModel().getStore('fileStore').load();

    },

    onClickFileHistoryBtn: function(view, record, fileId) {
        Ext.Msg.wait('Свойства листа', 'Запрос данных...');
        ASTD.model.FileModel.load(fileId, {
            scope: this,
            callback: function(record, operation, success) {
                Ext.Msg.hide();
                if(success){
                    if(view.isXType('file.filehistoryformview')){
                        view.getViewModel().set('prevFileVersion', record);
                    } else {
                        var fileHistoryForm = new ASTD.view.file.FileHistoryFormView({
                            region: 'center',
                            viewModel: {
                                data: {
                                    prevFileVersion: record
                                }
                            }
                        });
                        this.getView().remove(view);
                        this.getView().add(fileHistoryForm);
                    }
                }
            }
        });
        /*Ext.Ajax.request({
            url: record.getProxy().getUrl() + '/history/' + direction + '/' + record.getId(),
            method: 'GET',
            scope: this,
            callback: function(options, success, response) {
                Ext.Msg.hide();
                var responseText = Ext.decode(response.responseText);
                if(responseText.success){
                    if(view.isXType('file.filehistoryformview')){
                        view.getViewModel().get('prevFileVersion').set(responseText.item);
                    } else {
                        var fileHistoryForm = new ASTD.view.file.FileHistoryFormView({
                            region: 'center',
                            viewModel: {
                                data: {
                                    prevFileVersion: Ext.create('ASTD.model.FileModel', responseText.item)
                                }
                            }
                        });
                        this.getView().remove(view);
                        this.getView().add(fileHistoryForm);
                    }
                }
            }
        });*/
    },

    init: function() {
        this.listen({
            controller: {
                '#mainMoreSignsListViewController': {
                    clickDocList: this.onClickDocList
                },
                '#fileFormViewController': {
                    clickFileHistoryBtn: this.onClickFileHistoryBtn
                },
                '#fileRejectFormViewController': {
                    clickFileHistoryBtn: this.onClickFileHistoryBtn
                },
                '#fileHistoryFormViewController': {
                    clickDocList: this.onClickDocList,
                    viewFileBtnClick: this.onFileView,
                    downloadFileBtnClick: this.onDownloadFileBtnClick,
                    clickFileHistoryBtn: this.onClickFileHistoryBtn,
                    viewEcpPersonsBtnClick: this.onViewEcpPersonsBtnClick
                },
                '#fileListViewController': {
                    viewFileBtnClick: this.onFileView,
                    downloadFileBtnClick: this.onDownloadFileBtnClick,
                    viewEcpPersonsBtnClick: this.onViewEcpPersonsBtnClick
                }
            }
        });
    },

    onFileView: function(currentFile) {
                var win = window.open('', '_blank');
                win.location = currentFile.getProxy().getUrl() + '/view/' + currentFile.getId();
                win.focus();
    },

    onDownloadFileBtnClick: function(currentFile) {
        if(Ext.fly('downloadIframe')){
            Ext.fly('downloadIframe').destroy();
        }

        Ext.DomHelper.append(document.body, {
            tag: 'iframe',
            id:'downloadIframe',
            frameBorder: 0,
            width: 0,
            height: 0,
            css: 'display:none; visibility:hidden; height:0px; width:0px;',
            src: currentFile.getProxy().getUrl() + '/download/' + currentFile.getId()
        });
    },

    onViewEcpPersonsBtnClick: function(view, record) {
        var win = new ASTD.view.file.FileEcpPersonsListView({
            viewModel: {
                stores: {
                    ecpPersonsStore: record.ecpPersons()
                }
            }
        });

        win.show();
    },

    onClickCatalogList: function(view, record) {
        var prevCatalog = this.getViewModel().get('prev.catalog');
        var docList = this.lookupReference('docList');
        if(docList && prevCatalog && prevCatalog.getId() === record.getId()){
            return; // same click
        }

        var list = this.lookupReference('fileList');
        if(list){
            this.getView().remove(list);
        }

        list = this.lookupReference('fileHistoryForm');
        if(list){
            this.getView().remove(list);
        }

        list = this.lookupReference('auditList');
        if(list){
            this.getView().remove(list);
        }

        if(record.get('isCatalog')){
            var catalogList = this.lookupReference('catalogList');
            if(!catalogList.getSelectionModel().isSelected(record)){
                catalogList.getSelectionModel().select(record);
            }

            if(record.get('type') === 'SCHEME' /*|| record.get('type') === 'REJECTED' || record.get('type') === 'ARCHIVE'*/){
                if(!docList){
                    docList = new ASTD.view.doc.DocListView({
                        region: 'center',
                        listeners: {
                            clickDocList: 'onClickDocList'
                        }
                    });
                    this.getView().add(docList);
                    this.getViewModel().notify();
                } else {
                    docList.show();
                }
                // var isVirual = record.get('branchType') === 'REJECTED' || record.get('branchType') === 'ARCHIVE';
                Ext.Msg.wait("Загрузка", "Загрузка списка");
                docList.getStore().getProxy().setExtraParams({
                    catalogId: record.getId(),
                    branchType: this.getViewModel().get("current.branchType")
                });
                docList.getStore().load();
            } else {
                docList = this.lookupReference('docList');
                if(docList){
                    docList.hide();
                }
            }
        } else {
            docList = this.lookupReference('docList');
            if(docList){
                this.getView().remove(docList);
            }

            if(record.getId() === 'audit'){
                list = new ASTD.view.audit.AuditListView({
                    region: 'center'
                });
            }

            this.getView().add(list);
            this.getViewModel().notify();
            Ext.Msg.wait("Загрузка", "Загрузка списка");
            list.getStore().load();

        }
        this.getViewModel().set('prev.catalog', record);
    },

    onLoadCurrentUserInfo: function() {
        var currentUser = Ext.create('ASTD.model.UserModel');
        Ext.Ajax.request({
            url: currentUser.getProxy().getUrl() + '/current',
            method: 'GET',
            scope: this,
            callback: function(options, success, response) {
                //  this.lookupReference('catalogList').fireEvent('loadCatalogList', this.getView());
                var responseText = Ext.decode(response.responseText);
                if(responseText.success){
                    currentUser.set(responseText.item);
                    this.getViewModel().set('current.user', currentUser);
                }
            }
        });
    },

    onChangeBranchType: function(field, newValue, oldValue, eOpts) {
        var current = this.getViewModel().get('current');
        var bx = field.getBoxes();
        for( var i=0; i < bx.length; i++ ) {
            if(bx[i].lastValue) {
                current.branchTypeText = bx[i].boxLabel;
            }
        }
        current.branchType = newValue;
        // console.log(current.branchType + " - " + current.branchTypeText);
        if(current.doc && Ext.getCmp('idFileListView')) {
            this.onClickDocList(Ext.getCmp('idFileListView'), current.doc);
        }
    },

    onMoreSignsBtnClick: function(button, e, eOpts) {
        var centerRegion = this.getView().getLayout().centerRegion;
        var win = new ASTD.view.main.MainMoreSignsListView({
            viewModel: {
                data: {
                    tree: this.lookup('catalogList'),
                    view: centerRegion ? centerRegion : null
                }
            }
        });
        win.show();
        Ext.Msg.wait("Загрузка", "Загрузка списка");
        // win.getViewModel().getStore('moreSignsStore').load();
    }

});
