/*
 * File: app/view/main/MainSearchFilesListView.js
 *
 * This file was generated by Sencha Architect version 4.2.8.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.view.main.MainSearchFilesListView', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.mainsearchfileslistview',

    requires: [
        'ASTD.view.main.MainSearchFilesListViewModel',
        'ASTD.view.main.MainSearchFilesListViewController',
        'Ext.grid.column.Column',
        'Ext.view.Table',
        'Ext.toolbar.Paging',
        'Ext.button.Button',
        'Ext.form.field.Number',
        'Ext.toolbar.Separator'
    ],

    controller: 'main.mainsearchfileslistview',
    viewModel: {
        type: 'main.mainsearchfileslistview'
    },
    reference: 'searchlist',
    cls: 'more-list-view',
    id: 'mainSearchFilesListView',
    width: 900,
    collapsible: true,
    header: {
        iconCls: 'x-fa fa-list'
    },
    title: 'Поиск, листы',
    split: true,
    enableColumnHide: false,
    enableColumnMove: false,

    bind: {
        selection: '{current.file}',
        store: '{searchFilesStore}'
    },
    columns: [
        {
            xtype: 'gridcolumn',
            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                metaData.style = 'white-space:normal;';
                return value;
            },
            dataIndex: 'id',
            width: 150,
            text: 'Индивидуальный <br/>номер'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'listNum',
            text: 'Лист'
        },
        {
            xtype: 'gridcolumn',
            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                metaData.style = 'white-space:normal;';
                return value;
            },
            flex: 1,
            dataIndex: 'descr',
            text: 'Наименование'
        },
        {
            xtype: 'gridcolumn',
            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                metaData.style = 'white-space:normal;';
                return value;
            },
            flex: 1,
            defaultWidth: 132,
            dataIndex: 'statusText',
            tdCls: 'status_01',
            text: 'Статус'
        }
    ],
    listeners: {
        itemdblclick: 'onFileItemDblClick',
        expand: 'onExpand',
        collapse: 'onCollapse',
        unfloat: 'onUnfloat',
        float: 'onFloat'
    },
    dockedItems: [
        {
            xtype: 'pagingtoolbar',
            dock: 'bottom',
            displayInfo: true,
            bind: {
                store: '{searchFilesStore}'
            }
        },
        {
            xtype: 'button',
            dock: 'bottom',
            width: 100,
            iconCls: 'x-fa fa-check',
            text: 'Перейти',
            listeners: {
                click: 'onGoToSelectedFileClick'
            }
        },
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'numberfield',
                    reference: 'searchId',
                    width: 170,
                    fieldLabel: 'Номер',
                    labelWidth: 50
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'textfield',
                    reference: 'searchDescr',
                    fieldLabel: 'Наименование'
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'button',
                    iconCls: 'x-fa fa-search',
                    text: 'Поиск',
                    listeners: {
                        click: 'onSearchBtnClick'
                    }
                }
            ]
        }
    ]

});