/*
 * File: app/view/main/MainMoreRejectedListViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.view.main.MainMoreRejectedListViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.main.mainmorerejectedlistview',

    id: 'mainMoreSignsListViewController',

    onGoToSelectedDoc: function(record) {
                Ext.Msg.wait('Чертеж', 'Запрос данных...');
                ASTD.model.DocModel.load(record.get('docId'), {
                    scope: this,
                    params: {branchType: this.getViewModel().get("current.branchType")},
                    callback: function(doc, operation, success) {
                        Ext.Msg.hide();
                        if(success){
                           // Ext.Msg.wait('Каталог', 'Запрос данных...');
                            var currentCatalog = this.getViewModel().get('current.catalog');
                            if(!currentCatalog || doc.get('catalogId') !== currentCatalog.getId()){
                                var tree = this.getViewModel().get('tree');
                                currentCatalog = tree.getRootNode().findChildBy(function(node){
                                    return node.getId() === doc.get('catalogId');
                                }, this, true);
                                if(!currentCatalog){
                                    return;
                                }

                                tree.selectPath(currentCatalog.getPath());
                                this.getViewModel().set('current.catalog', currentCatalog);
                            }

                            var currentDoc = this.getViewModel().get('current.doc');
                            if(!currentDoc || doc.getId() !== currentDoc.getId()){
                               this.getViewModel().set('current.doc', doc);
                            }

                            this.fireEvent('clickDocList', this.getViewModel().get('view'), this.getViewModel().get('current.doc'));
                            this.getView().close();
                        }
                    }
                });
    },

    onDocItemDblClick: function(dataview, record, item, index, e, eOpts) {
        // this.fireEvent('clickFileHistoryBtn', this.getView());
        this.onGoToSelectedDoc(record);
    },

    onGoToSelectedDocClick: function(button, e, eOpts) {
        var record = this.lookup('moreRejectedList').getSelection()[0];
        if(!ASTD.Utils.isSelected(record)){
            return false;
        }
        this.onGoToSelectedDoc(record);
    },

    onCloseClick: function(button, e, eOpts) {
        this.getView().close();
    }

});
