/*
 * File: app/view/main/MainSearchDocsListView.js
 *
 * This file was generated by Sencha Architect version 4.2.8.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.view.main.MainSearchDocsListView', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.mainsearchdocslistview',

    requires: [
        'ASTD.view.main.MainSearchDocsListViewModel',
        'ASTD.view.main.MainSearchDocsListViewController',
        'Ext.grid.column.Column',
        'Ext.view.Table',
        'Ext.toolbar.Paging',
        'Ext.button.Button',
        'Ext.form.field.Text',
        'Ext.toolbar.Separator'
    ],

    controller: 'main.mainsearchdocslistview',
    viewModel: {
        type: 'main.mainsearchdocslistview'
    },
    reference: 'searchlist',
    cls: 'more-list-view',
    id: 'mainSearchDocsListView',
    width: 900,
    collapsible: true,
    header: {
        iconCls: 'x-fa fa-list'
    },
    title: 'Поиск, чертежи',
    split: true,
    enableColumnHide: false,
    enableColumnMove: false,

    bind: {
        selection: '{current.searchDoc}',
        store: '{searchDocsStore}'
    },
    columns: [
        {
            xtype: 'gridcolumn',
            width: 80,
            dataIndex: 'npp',
            text: '№ п/п'
        },
        {
            xtype: 'gridcolumn',
            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                metaData.style = 'white-space:normal;';
                return record.get('rootCatalogName') + ' > ' + record.get('docCatalogName');
            },
            width: 150,
            dataIndex: 'docCatalogName',
            text: 'Путь'
        },
        {
            xtype: 'gridcolumn',
            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                metaData.style = 'white-space:normal;';
                return value;
            },
            dataIndex: 'num',
            text: 'Номер'
        },
        {
            xtype: 'gridcolumn',
            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                metaData.style = 'white-space:normal;';
                return value;
            },
            flex: 1,
            dataIndex: 'descr',
            text: 'Наименование'
        },
        {
            xtype: 'gridcolumn',
            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                metaData.style = 'white-space:normal;';
                return record.get('filesDefaultCount') + ' / ' +
                record.get('filesApprovedCount')+ ' / ' +
                record.get('filesArchiveCount')+ ' / ' +
                record.get('filesAllCount');
            },
            width: 180,
            dataIndex: 'filesAllCount',
            text: 'Листы<br> (раб/утв/арх/всего)'
        }
    ],
    listeners: {
        itemdblclick: 'onDocItemDblClick',
        expand: 'onExpand',
        collapse: 'onCollapse',
        unfloat: 'onUnfloat',
        float: 'onFloat'
    },
    dockedItems: [
        {
            xtype: 'pagingtoolbar',
            dock: 'bottom',
            displayInfo: true,
            bind: {
                store: '{searchDocsStore}'
            }
        },
        {
            xtype: 'button',
            dock: 'bottom',
            width: 100,
            iconCls: 'x-fa fa-check',
            text: 'Перейти',
            listeners: {
                click: 'onGoToSelectedDocClick'
            }
        },
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'textfield',
                    reference: 'searchNum',
                    width: 170,
                    fieldLabel: 'Номер',
                    labelWidth: 50
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'textfield',
                    reference: 'searchDescr',
                    fieldLabel: 'Наименование'
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'button',
                    iconCls: 'x-fa fa-search',
                    text: 'Поиск',
                    listeners: {
                        click: 'onSearchBtnClick'
                    }
                }
            ]
        }
    ]

});