/*
 * File: app/view/main/MainMoreRejectedListView.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.view.main.MainMoreRejectedListView', {
    extend: 'Ext.window.Window',
    alias: 'widget.main.mainmorerejectedlistview',

    requires: [
        'ASTD.view.main.MainMoreRejectedListViewModel',
        'ASTD.view.main.MainMoreRejectedListViewController',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Number',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    controller: 'main.mainmorerejectedlistview',
    viewModel: {
        type: 'main.mainmorerejectedlistview'
    },
    modal: true,
    height: 600,
    width: '90%',
    layout: 'fit',
    header: {
        glyph: 'xf05e@FontAwesome'
    },
    title: 'Чертежи, отклоненные',
    maximizable: true,

    items: [
        {
            xtype: 'gridpanel',
            reference: 'moreRejectedList',
            enableColumnHide: false,
            enableColumnMove: false,
            sortableColumns: false,
            bind: {
                store: '{moreRejectedStore}'
            },
            columns: [
                {
                    xtype: 'gridcolumn',
                    flex: 1,
                    dataIndex: 'shCh',
                    text: 'ШЧ'
                },
                {
                    xtype: 'gridcolumn',
                    flex: 1,
                    dataIndex: 'stnLine',
                    text: 'Станция/перегон'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        metaData.style = 'white-space:normal;';
                        return value;
                    },
                    flex: 1,
                    dataIndex: 'num',
                    text: 'Номер'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        metaData.style = 'white-space:normal;';
                        return value;
                    },
                    flex: 2,
                    dataIndex: 'descr',
                    text: 'Наименование'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        metaData.style = 'white-space:normal;';
                        return value;
                    },
                    flex: 1,
                    dataIndex: 'dateShch',
                    text: 'Подписано<br>ШЧ'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'signNum',
                    text: 'На подпись',
                    format: '0'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        metaData.style = 'white-space:normal;';
                        return value;
                    },
                    flex: 2,
                    dataIndex: 'noteShl',
                    text: 'Комментарий',
                    bind: {
                        hidden: '{isNoteHidden}'
                    }
                }
            ],
            listeners: {
                itemdblclick: 'onDocItemDblClick'
            }
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'bottom',
            ui: 'footer',
            layout: {
                type: 'hbox',
                pack: 'end'
            },
            items: [
                {
                    xtype: 'button',
                    glyph: 'xf00c@FontAwesome',
                    text: 'Перейти',
                    listeners: {
                        click: 'onGoToSelectedDocClick'
                    }
                },
                {
                    xtype: 'button',
                    glyph: 'xf057@FontAwesome',
                    text: 'Закрыть',
                    listeners: {
                        click: 'onCloseClick'
                    }
                }
            ]
        }
    ]

});