/*
 * File: app/view/main/MainMoreRejectedListView.js
 *
 * This file was generated by Sencha Architect version 4.2.8.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.view.main.MainMoreRejectedListView', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.mainmorerejectedlistview',

    requires: [
        'ASTD.view.main.MainMoreRejectedListViewModel',
        'ASTD.view.main.MainMoreRejectedListViewController',
        'Ext.grid.column.Number',
        'Ext.view.Table',
        'Ext.toolbar.Paging',
        'Ext.button.Button'
    ],

    controller: 'main.mainmorerejectedlistview',
    viewModel: {
        type: 'main.mainmorerejectedlistview'
    },
    reference: 'morelist',
    cls: 'more-list-view',
    id: 'mainMoreRejectedListView',
    width: 900,
    collapsible: true,
    header: {
        iconCls: 'x-fa fa-list'
    },
    title: 'Чертежи, отклоненные',
    split: true,
    enableColumnHide: false,
    enableColumnMove: false,

    bind: {
        selection: '{current.rejectedFile}',
        store: '{moreRejectedStore}'
    },
    columns: [
        {
            xtype: 'gridcolumn',
            flex: 1,
            dataIndex: 'shCh',
            text: 'ШЧ'
        },
        {
            xtype: 'gridcolumn',
            flex: 1,
            dataIndex: 'stnLine',
            text: 'Станция/<br/>перегон'
        },
        {
            xtype: 'gridcolumn',
            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                metaData.style = 'white-space:normal;';
                return value;
            },
            flex: 1,
            dataIndex: 'num',
            text: 'Номер'
        },
        {
            xtype: 'gridcolumn',
            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                metaData.style = 'white-space:normal;';
                return value;
            },
            flex: 2,
            dataIndex: 'descr',
            text: 'Наименование'
        },
        {
            xtype: 'gridcolumn',
            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                metaData.style = 'white-space:normal;';
                return value;
            },
            flex: 1,
            dataIndex: 'dateSign',
            text: 'Отклонено'
        },
        {
            xtype: 'numbercolumn',
            flex: 1,
            dataIndex: 'listCount',
            text: 'Листов',
            format: '0'
        },
        {
            xtype: 'gridcolumn',
            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                metaData.style = 'white-space:normal;';
                return value;
            },
            flex: 2,
            dataIndex: 'noteShl',
            text: 'Комментарий',
            bind: {
                hidden: '{isNoteHidden}'
            }
        },
        {
            xtype: 'gridcolumn',
            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                metaData.style = 'white-space:normal;';
                return value;
            },
            flex: 2,
            dataIndex: 'msg',
            text: 'Причина'
        }
    ],
    listeners: {
        itemdblclick: 'onDocItemDblClick',
        expand: 'onExpand',
        collapse: 'onCollapse',
        float: 'onFloat',
        unfloat: 'onUnfloat',
        resize: 'onResize'
    },
    dockedItems: [
        {
            xtype: 'pagingtoolbar',
            dock: 'bottom',
            displayInfo: true,
            bind: {
                store: '{moreRejectedStore}'
            }
        },
        {
            xtype: 'button',
            dock: 'bottom',
            width: 100,
            iconCls: 'x-fa fa-check',
            text: 'Перейти',
            listeners: {
                click: 'onGoToSelectedDocClick'
            }
        }
    ]

});