/*
 * File: app/view/main/MainMoreApprovedListView.js
 *
 * This file was generated by Sencha Architect version 4.2.8.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.view.main.MainMoreApprovedListView', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.mainmoreapprovedlistview',

    requires: [
        'ASTD.view.main.MainMoreApprovedListViewModel',
        'ASTD.view.main.MainMoreApprovedListViewController',
        'Ext.grid.column.Boolean',
        'Ext.grid.column.Number',
        'Ext.view.Table',
        'Ext.toolbar.Paging',
        'Ext.button.Button'
    ],

    controller: 'main.mainmoreapprovedlistview',
    viewModel: {
        type: 'main.mainmoreapprovedlistview'
    },
    reference: 'morelist',
    cls: 'more-list-view',
    id: 'mainMoreApprovedListView',
    width: 900,
    collapsible: true,
    header: {
        iconCls: 'x-fa fa-list'
    },
    title: 'Чертежи, утвержденные',
    split: true,
    enableColumnHide: false,
    enableColumnMove: false,

    bind: {
        selection: '{current.approvedFile}',
        store: '{moreApprovedStore}'
    },
    columns: [
        {
            xtype: 'booleancolumn',
            style: 'font: 23px/2 FontAwesome;',
            width: 40,
            sortable: false,
            dataIndex: 'paperShL',
            tdCls: 'glyph_01',
            text: '&#128206;',
            falseText: ' ',
            trueText: '&#128206;',
            bind: {
                hidden: '{current.user.positionId !== 5}'
            }
        },
        {
            xtype: 'booleancolumn',
            style: 'font: 23px/2 FontAwesome;',
            width: 40,
            sortable: false,
            dataIndex: 'paperShChTD',
            tdCls: 'glyph_01',
            text: '&#128206;',
            falseText: ' ',
            trueText: '&#128206;',
            bind: {
                hidden: '{current.user.positionId !== 9}'
            }
        },
        {
            xtype: 'gridcolumn',
            flex: 1,
            dataIndex: 'shCh',
            text: 'ШЧ'
        },
        {
            xtype: 'gridcolumn',
            flex: 1,
            dataIndex: 'stnLine',
            text: 'Станция/перегон'
        },
        {
            xtype: 'gridcolumn',
            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                metaData.style = 'white-space:normal;';
                return value;
            },
            flex: 1,
            dataIndex: 'num',
            text: 'Номер'
        },
        {
            xtype: 'gridcolumn',
            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                metaData.style = 'white-space:normal;';
                return value;
            },
            flex: 2,
            dataIndex: 'descr',
            text: 'Наименование'
        },
        {
            xtype: 'gridcolumn',
            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                metaData.style = 'white-space:normal;';
                return value;
            },
            flex: 1,
            dataIndex: 'dateSign',
            text: 'Подписано'
        },
        {
            xtype: 'numbercolumn',
            flex: 1,
            dataIndex: 'listCount',
            text: 'Листов',
            format: '0'
        }
    ],
    listeners: {
        itemdblclick: 'onDocItemDblClick',
        expand: 'onExpand',
        collapse: 'onCollapse',
        float: 'onFloat',
        unfloat: 'onUnfloat',
        resize: 'onResize'
    },
    dockedItems: [
        {
            xtype: 'pagingtoolbar',
            dock: 'bottom',
            displayInfo: true,
            bind: {
                store: '{moreApprovedStore}'
            }
        },
        {
            xtype: 'button',
            dock: 'bottom',
            iconCls: 'x-fa fa-check',
            text: 'Перейти',
            listeners: {
                click: 'onGoToSelectedDocClick'
            }
        }
    ]

});