/*
 * File: app/view/main/MainMoreSignsListViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.8.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.view.main.MainMoreSignsListViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.main.mainmoresignslistview',

    id: 'mainMoreSignsListViewController',

    onGoToSelectedDoc: function(record) {
        this.fireEvent('goToSelectedDoc', record.get('docId'), this.getView(), 'DEFAULT');
    },

    onDocItemDblClick: function(dataview, record, item, index, e, eOpts) {
        this.onGoToSelectedDoc(record);
    },

    onGoToSelectedDocClick: function(button, e, eOpts) {
        var record = this.getViewModel().get('current.signFile');
        if(!ASTD.Utils.isSelected(record)){
            return false;
        }
        this.onGoToSelectedDoc(record);
    },

    onExpand: function(p, eOpts) {
        this.fireEvent('toggleCollapse', this.getView());
    },

    onCollapse: function(p, eOpts) {
        this.fireEvent('toggleCollapse', this.getView());
    },

    onUnfloat: function(eOpts) {
        this.fireEvent('toggleCollapse', this.getView());
    },

    onFloat: function(eOpts) {
        this.fireEvent('toggleCollapse', this.getView());
    },

    onResize: function(component, width, height, oldWidth, oldHeight, eOpts) {
        this.fireEvent('resize', width);
    }

});
