/*
 * File: app/view/main/MainViewModel.js
 *
 * This file was generated by Sencha Architect version 4.2.8.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.view.main.MainViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.main.mainview',

    requires: [
        'Ext.app.bind.Formula'
    ],

    data: {
        current: {
            catalog: null,
            doc: null,
            file: null,
            user: null,
            branchType: 'DEFAULT',
            branchTypeText: null
        },
        prev: {
            catalog: null
        }
    },

    formulas: {
        isMoreSignsBtnHidden: {
            get: function(data) {
                var user = this.get('current.user');
                if(!user) {
                    return true;
                }
                return user.get('positionId') === 33;
            },
            bind: {
                bindTo: '{current.user}',
                deep: true
            }
        },
        isMoreRejectedBtnHidden: {
            get: function(data) {
                var user = this.get('current.user');
                if(!user) {
                    return true;
                }
                return user.get('positionId') === 33;
            },
            bind: {
                bindTo: '{current.user}',
                deep: true
            }
        },
        isDefaultRadioHidden: {
            get: function(data) {
                var user = this.get('current.user');
                if(!user) {
                    return true;
                }
                return user.get('positionId') === 33;
            },
            bind: {
                bindTo: '{current.user}',
                deep: true
            }
        },
        isApprovedRadioHidden: {
            get: function(data) {
                var user = this.get('current.user');
                if(!user) {
                    return true;
                }

            },
            bind: {
                bindTo: '{current.user}',
                deep: true
            }
        },
        isArchiveRadioHidden: {
            get: function(data) {
                var user = this.get('current.user');
                if(!user) {
                    return true;
                }
                return user.get('positionId') === 33;
            },
            bind: {
                bindTo: '{current.user}',
                deep: true
            }
        },
        isMoreSignsAssureBtnHidden: {
            get: function(data) {
                var user = this.get('current.user');
                if(!user) {
                    return true;
                }
                return user.get('positionId') !== 5;
            },
            bind: {
                bindTo: '{current.user}',
                deep: true
            }
        }
    }

});