/*
 * File: app/view/main/MainViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.8.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.view.main.MainViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.main.mainview',

    onClickDocList: function(view, record) {
            if(view){
                this.getView().remove(view);
            }

            var fileList = new ASTD.view.file.FileListView({
                region: 'center',
                viewModel: {
                    data: {
                        docId: record.getId()
                    }
                },
                listeners: {
                    clickFileHistoryBtn: 'onClickFileHistoryBtn'
                }
            });
            this.getView().add(fileList);
            this.getViewModel().notify();
            Ext.Msg.wait("Загрузка", "Загрузка списка");
            //fileList.getStore().load({params:{docId: record.getId(), branchType: record.get('branchType')}});
            fileList.getViewModel().getStore('fileStore').getProxy().setExtraParams({
                docId: record.getId(),
                branchType: this.getViewModel().get("current.branchType")
            });
            fileList.getViewModel().getStore('fileStore').load();

    },

    onClickFileHistoryBtn: function(view, record, fileId) {
        Ext.Msg.wait('Свойства листа', 'Запрос данных...');
        ASTD.model.FileModel.load(fileId, {
            scope: this,
            callback: function(record, operation, success) {
                Ext.Msg.hide();
                if(success){
                    if(view.isXType('file.filehistoryformview')){
                        view.getViewModel().set('prevFileVersion', record);
                    } else {
                        var fileHistoryForm = new ASTD.view.file.FileHistoryFormView({
                            region: 'center',
                            viewModel: {
                                data: {
                                    prevFileVersion: record
                                }
                            }
                        });
                        this.getView().remove(view);
                        this.getView().add(fileHistoryForm);
                    }
                }
            }
        });

    },

    init: function() {
        this.listen({
            component: {
                '#mainMoreSignsListView': {
                    clickDocList: this.onClickDocList
                },
                '#mainMoreSignsAssureListView': {
                    clickDocList: this.onClickDocList
                },
                '#mainMoreRejectedListView': {
                    clickDocList: this.onClickDocList
                },
                '#mainMoreApprovedListView': {
                    clickDocList: this.onClickDocList
                }
            },
            controller: {
                '#mainMoreSignsListViewController': {
                    goToSelectedDoc: this.onGoToSelectedDoc,
                    toggleCollapse: this.onToggleMoreListCollapse
                },
                '#mainMoreSignsAssureListViewController': {
                    goToSelectedDoc: this.onGoToSelectedDoc,
                    toggleCollapse: this.onToggleMoreListCollapse
                },
                '#mainMoreRejectedListViewController': {
                    goToSelectedDoc: this.onGoToSelectedDoc,
                    toggleCollapse: this.onToggleMoreListCollapse
                },
                '#mainMoreApprovedListViewController': {
                    goToSelectedDoc: this.onGoToSelectedDoc,
                    toggleCollapse: this.onToggleMoreListCollapse
                },
                '#mainSearchDocsListViewController': {
                  //  goToSelectedDoc: this.onGoToSelectedDoc,
                    toggleCollapse: this.onToggleMoreListCollapse
                },
                '#fileFormViewController': {
                    clickFileHistoryBtn: this.onClickFileHistoryBtn
                },
                '#fileRejectFormViewController': {
                    clickFileHistoryBtn: this.onClickFileHistoryBtn
                },
                '#fileHistoryFormViewController': {
                    clickDocList: this.onClickDocList,
                    viewFileBtnClick: this.onFileView,
                    downloadFileBtnClick: this.onDownloadFileBtnClick,
                    clickFileHistoryBtn: this.onClickFileHistoryBtn,
                    viewEcpPersonsBtnClick: this.onViewEcpPersonsBtnClick
                },
                '#fileListViewController': {
                    viewFileBtnClick: this.onFileView,
                    downloadFileBtnClick: this.onDownloadFileBtnClick,
                    viewEcpPersonsBtnClick: this.onViewEcpPersonsBtnClick
                }
            }
        });
    },

    onFileView: function(currentFile, view, isFileView) {
                this.fileViewOrDownload(currentFile, view, isFileView);
    },

    onDownloadFileBtnClick: function(currentFile, view, isFileView) {
        this.fileViewOrDownload(currentFile, view, isFileView);
    },

    onViewEcpPersonsBtnClick: function(view, record) {
        var win = new ASTD.view.file.FileEcpPersonsListView({
            viewModel: {
                stores: {
                    ecpPersonsStore: record.ecpPersons()
                }
            }
        });

        win.show();
    },

    updateHeaderBranchTypeSelection: function(currentUser) {
        if(currentUser.get('positionId') === 33){
            this.getViewModel().set('current.branchType', 'APPROVED');
        }
    },

    onGoToSelectedDoc: function(docId, view, branchType) {
        Ext.Msg.wait('Чертеж', 'Запрос данных...');
        var viewModel = view.getViewModel();
        ASTD.model.DocModel.load(docId, {
            scope: this,
            params: {branchType: viewModel.get("current.branchType")},
            callback: function(doc, operation, success) {
                Ext.Msg.hide();
                if(success){
                    var currentCatalog = viewModel.get('current.catalog');
                    if(!currentCatalog || doc.get('catalogId') !== currentCatalog.getId()){
                        var tree = viewModel.get('tree');
                        currentCatalog = tree.getRootNode().findChildBy(function(node){
                            return node.getId() === doc.get('catalogId');
                        }, this, true);
                        if(!currentCatalog){
                            return;
                        }

                        tree.selectPath(currentCatalog.getPath());
                        viewModel.set('current.catalog', currentCatalog);
                    }

                    var currentDoc = viewModel.get('current.doc');
                    if(!currentDoc || doc.getId() !== currentDoc.getId()){
                        viewModel.set('current.doc', doc);
                    }

                    this.lookup('headerRadioBranchType').setValue(branchType);

                    view.fireEvent('clickDocList', this.getView().getLayout().centerRegion, viewModel.get('current.doc'));
                    view.collapse();
                   // view.close();
                }
            }

        });
    },

    fileViewOrDownload: function(currentFile, view, isFileView) {
        var fileUrl = currentFile.getProxy().getUrl();
                view.setLoading(true);
                Ext.Ajax.request({
                    url: fileUrl + '/check/ecp/' + currentFile.getId(),
                    method: 'GET',
                    scope: this,
                    callback: function (options, success, response) {
                        view.setLoading(false);
                        var responseText = Ext.decode(response.responseText);
                        var newFile = responseText['item'];
                        if (view.isXType('form')) {
                            if (currentFile.get('status') === 'INVALID' && newFile['status'] !== 'INVALID') {
                                view.lookup('fileview').setHtml(view.getViewModel().get('getEmbedFileHtml'));
                            } else if (currentFile.get('status') !== 'INVALID' && newFile['status'] === 'INVALID') {
                                view.lookup('fileview').setHtml('Подпись не верна');
                            }
                        }
                        currentFile.set('status', newFile['status']);
                        currentFile.set('statusText', newFile['statusText']);
                        currentFile.set('statusModifiedBy', newFile['statusModifiedBy']);

                        // if (responseText.success) {
                        if (success) {
                            if(isFileView) {
                                var win = window.open('', '_blank');
                                win.location = fileUrl + '/view/' + currentFile.getId();
                                win.focus();
                            } else {
                                if(Ext.fly('downloadIframe')){
                                    Ext.fly('downloadIframe').destroy();
                                }

                                Ext.DomHelper.append(document.body, {
                                    tag: 'iframe',
                                    id:'downloadIframe',
                                    frameBorder: 0,
                                    width: 0,
                                    height: 0,
                                    css: 'display:none; visibility:hidden; height:0px; width:0px;',
                                    src: fileUrl + '/download/' + currentFile.getId()
                                });
                            }
                        } else {
                            Ext.Msg.show({
                                title: 'Ошибка',
                                msg: responseText.message,
                                buttons: Ext.Msg.OK,
                                icon: Ext.Msg.ERROR
                            });
                        }
                    }
                });
    },

    showEastPanel: function(xtype) {
        var morelist = this.getView().lookup('morelist') || this.getView().lookup('searchlist');
        if(!morelist || !morelist.isXType(xtype, true)) {
            var fileList = Ext.widget(xtype, {
                region: 'east',
                viewModel: {
                    data: {
                        tree: this.lookup('catalogList')
                    }
                }
            });
            if(morelist) {
                this.getView().remove(morelist);
            }
            this.getView().add(fileList);
        } else {
            morelist.toggleCollapse();
            //this.getView().updateLayout();
        }
    },

    onToggleMoreListCollapse: function(panel) {
        this.getView().updateLayout();
    },

    onClickCatalogList: function(view, record) {
        var prevCatalog = this.getViewModel().get('prev.catalog');
        var docList = this.lookupReference('docList');
        if(docList && prevCatalog && prevCatalog.getId() === record.getId()){
            return; // same click
        }

        var list = this.lookupReference('fileList');
        if(list){
            this.getView().remove(list);
        }

        list = this.lookupReference('fileHistoryForm');
        if(list){
            this.getView().remove(list);
        }

        list = this.lookupReference('auditList');
        if(list){
            this.getView().remove(list);
        }

        list = this.lookupReference('userList');
        if(list){
            this.getView().remove(list);
        }

        if(record.get('isCatalog')){
            var catalogList = this.lookupReference('catalogList');
            if(!catalogList.getSelectionModel().isSelected(record)){
                catalogList.getSelectionModel().select(record);
            }

            if(record.get('type') === 'SCHEME' /*|| record.get('type') === 'REJECTED' || record.get('type') === 'ARCHIVE'*/){
                if(!docList){
                    docList = new ASTD.view.doc.DocListView({
                        region: 'center',
                        listeners: {
                            clickDocList: 'onClickDocList'
                        }
                    });
                    this.getView().add(docList);
                    this.getViewModel().notify();
                } else {
                    docList.show();
                }
                // var isVirual = record.get('branchType') === 'REJECTED' || record.get('branchType') === 'ARCHIVE';
                Ext.Msg.wait("Загрузка", "Загрузка списка");
                docList.getStore().getProxy().setExtraParams({
                    catalogId: record.getId(),
                    branchType: this.getViewModel().get("current.branchType")
                });
                docList.getStore().load();
            } else {
                docList = this.lookupReference('docList');
                if(docList){
                    docList.hide();
                }
            }
        } else {
            docList = this.lookupReference('docList');
            if(docList){
                this.getView().remove(docList);
            }

            if(record.getId() === 'audit'){
                list = new ASTD.view.audit.AuditListView({
                    region: 'center'
                });
            }

            if(record.getId() === 'user'){
                list = new ASTD.view.user.UserListView({
                    region: 'center'
                });
            }

            this.getView().add(list);
            this.getViewModel().notify();
            Ext.Msg.wait("Загрузка", "Загрузка списка");
            list.getStore().load();

        }
        this.getViewModel().set('prev.catalog', record);
    },

    onLoadCurrentUserInfo: function() {
        var currentUser = Ext.create('ASTD.model.UserModel');
        Ext.Ajax.request({
            url: currentUser.getProxy().getUrl() + '/current',
            method: 'GET',
            scope: this,
            callback: function(options, success, response) {
                //  this.lookupReference('catalogList').fireEvent('loadCatalogList', this.getView());
                var responseText = Ext.decode(response.responseText);
                if(responseText.success){
                    currentUser.set(responseText.item);
                    this.getViewModel().set('current.user', currentUser);
                    this.updateHeaderBranchTypeSelection(currentUser);
                }
            }
        });
    },

    onChangeBranchType: function(field, newValue, oldValue, eOpts) {
        var current = this.getViewModel().get('current');
        var bx = field.getBoxes();
        for( var i=0; i < bx.length; i++ ) {
            if(bx[i].lastValue) {
                current.branchTypeText = bx[i].boxLabel;
            }
        }
        current.branchType = newValue;
        // console.log(current.branchType + " - " + current.branchTypeText);
        if(current.doc && Ext.getCmp('idFileListView')) {
            this.onClickDocList(Ext.getCmp('idFileListView'), current.doc);
        }
    },

    onSearchDocsBtnClick: function(item, e, eOpts) {
        this.showEastPanel('mainsearchdocslistview');
    },

    onSearchFilesBtnClick: function(item, e, eOpts) {
        this.showEastPanel('mainsearchfileslistview');
    },

    onMoreSignsBtnClick: function(button, e, eOpts) {
        this.showEastPanel('mainmoresignslistview');
    },

    onMoreSignsAssureBtnClick: function(button, e, eOpts) {
        this.showEastPanel('mainmoresignsassurelistview');
    },

    onMoreApprovedBtnClick: function(button, e, eOpts) {
        this.showEastPanel('mainmoreapprovedlistview');
    },

    onMoreRejectedBtnClick: function(button, e, eOpts) {
        this.showEastPanel('mainmorerejectedlistview');
    }

});
