/*
 * File: app/view/main/MainSearchDocsListViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.8.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.view.main.MainSearchDocsListViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.main.mainsearchdocslistview',

    id: 'mainSearchDocsListViewController',

    onGoToSelectedDoc: function(record) {
        this.fireEvent('goToSelectedDoc', record.get('id'), this.getView(), 'DEFAULT'); // go into selected doc
    },

    onDocItemDblClick: function(dataview, record, item, index, e, eOpts) {
        this.onGoToSelectedDoc(record);
    },

    onExpand: function(p, eOpts) {
        this.fireEvent('toggleCollapse', this.getView());
    },

    onCollapse: function(p, eOpts) {
        this.fireEvent('toggleCollapse', this.getView());
    },

    onUnfloat: function(eOpts) {
        this.fireEvent('toggleCollapse', this.getView());
    },

    onFloat: function(eOpts) {
        this.fireEvent('toggleCollapse', this.getView());
    },

    onGoToSelectedDocClick: function(button, e, eOpts) {
        var record = this.getViewModel().get('current.searchDoc');
        if(!ASTD.Utils.isSelected(record)){
            return false;
        }
        this.onGoToSelectedDoc(record);
    },

    onSearchBtnClick: function(button, e, eOpts) {
        var searchNumVal = this.lookup('searchNum').getValue().trim();
        var searchDescrVal = this.lookup('searchDescr').getValue().trim();
        if(!searchNumVal && !searchDescrVal) {
            Ext.Msg.alert('Ошибка', 'Незаполены поля для поиска');
            return;
        }

        this.getStore('searchDocsStore').getFilters().add(
        new Ext.util.Filter({
            property: 'num',
            value: searchNumVal,
            operator: '='
        }),
        new Ext.util.Filter({
            property: 'descr',
            value: searchDescrVal,
            operator: 'like'
        })
        );
    }

});
