/*
 * File: app/view/main/MainSearchFilesListViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.8.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.view.main.MainSearchFilesListViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.main.mainsearchfileslistview',

    id: 'mainSearchFilesListViewController',

    onGoToSelectedFile: function(record) {
        this.fireEvent('goToSelectedDoc', record.get('id'), this.getView(), record.get('branchType'));
    },

    onFileItemDblClick: function(dataview, record, item, index, e, eOpts) {
        this.onGoToSelectedFile(record);
    },

    onExpand: function(p, eOpts) {
        this.fireEvent('toggleCollapse', this.getView());
    },

    onCollapse: function(p, eOpts) {
        this.fireEvent('toggleCollapse', this.getView());
    },

    onUnfloat: function(eOpts) {
        this.fireEvent('toggleCollapse', this.getView());
    },

    onFloat: function(eOpts) {
        this.fireEvent('toggleCollapse', this.getView());
    },

    onGoToSelectedFileClick: function(button, e, eOpts) {
        var record = this.getViewModel().get('current.file');
        if(!ASTD.Utils.isSelected(record)){
            return false;
        }
        this.onGoToSelectedFile(record);
    },

    onSearchBtnClick: function(button, e, eOpts) {
        var searchIdVal = this.lookup('searchId').getValue().trim();
        var searchDescrVal = this.lookup('searchDescr').getValue().trim();
        if(!searchIdVal && !searchDescrVal) {
            Ext.Msg.alert('Ошибка', 'Незаполены поля для поиска');
            return;
        }

        this.getStore('searchFilesStore').getFilters().add(
        new Ext.util.Filter({
            property: 'id',
            value: searchIdVal,
            operator: '='
        }),
        new Ext.util.Filter({
            property: 'descr',
            value: searchDescrVal,
            operator: 'like'
        })
        );
    }

});
