/*
 * File: app/view/main/MainView.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.view.main.MainView', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.main',

    requires: [
        'ASTD.view.main.MainViewModel',
        'ASTD.view.main.MainViewController',
        'ASTD.view.catalog.CatalogListView',
        'Ext.tree.Panel',
        'Ext.Img',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Separator',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.button.Button'
    ],

    controller: 'main.mainview',
    viewModel: {
        type: 'main.mainview'
    },
    reference: 'main',
    layout: 'border',

    items: [
        {
            xtype: 'catalog.cataloglistview',
            reference: 'catalogList',
            region: 'west',
            listeners: {
                clickCatalogList: 'onClickCatalogList',
                loadCurrentUserInfo: 'onLoadCurrentUserInfo'
            }
        },
        {
            xtype: 'container',
            region: 'north',
            id: 'app-header',
            layout: {
                type: 'hbox',
                align: 'middle'
            },
            items: [
                {
                    xtype: 'image',
                    height: 70,
                    id: 'app-header-logo',
                    width: 150,
                    src: './resources/images/logo_bzhd.png'
                },
                {
                    xtype: 'component',
                    flex: 1,
                    html: '<h1>АС «ТД Ш»</h1>',
                    id: 'app-header-text'
                },
                {
                    xtype: 'container',
                    flex: 1,
                    height: 70,
                    id: 'app-header-right',
                    layout: {
                        type: 'vbox',
                        align: 'right'
                    },
                    items: [
                        {
                            xtype: 'component',
                            id: 'app-header-user',
                            bind: {
                                html: '<h3><label>{current.user.positionName}</label> {current.user.name}</h3>'
                            }
                        },
                        {
                            xtype: 'toolbar',
                            flex: 1,
                            ui: 'footer',
                            items: [
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'radiogroup',
                                    id: 'app-header-branch-type',
                                    fieldLabel: 'Листы',
                                    labelStyle: 'color: #676767;',
                                    labelWidth: 60,
                                    simpleValue: true,
                                    bind: {
                                        value: '{current.branchType}'
                                    },
                                    items: [
                                        {
                                            xtype: 'radiofield',
                                            width: 100,
                                            name: 'branchType',
                                            boxLabel: 'В работе',
                                            inputValue: 'DEFAULT'
                                        },
                                        {
                                            xtype: 'radiofield',
                                            width: 130,
                                            name: 'branchType',
                                            boxLabel: 'Утверждено',
                                            inputValue: 'APPROVED'
                                        },
                                        {
                                            xtype: 'radiofield',
                                            width: 80,
                                            name: 'branchType',
                                            boxLabel: 'Архив',
                                            inputValue: 'ARCHIVE'
                                        }
                                    ],
                                    listeners: {
                                        change: 'onChangeBranchType'
                                    }
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    glyph: 'xf002@FontAwesome',
                                    text: 'На подпись',
                                    listeners: {
                                        click: 'onMoreSignsBtnClick'
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});