/*
 * File: app/view/main/MainMoreSignsAssureListView.js
 *
 * This file was generated by Sencha Architect version 4.2.8.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.view.main.MainMoreSignsAssureListView', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.mainmoresignsassurelistview',

    requires: [
        'ASTD.view.main.MainMoreSignsAssureListViewModel',
        'ASTD.view.main.MainMoreSignsAssureListViewController',
        'Ext.grid.column.Number',
        'Ext.view.Table',
        'Ext.toolbar.Paging',
        'Ext.button.Button'
    ],

    controller: 'main.mainmoresignsassurelistview',
    viewModel: {
        type: 'main.mainmoresignsassurelistview'
    },
    reference: 'morelist',
    cls: 'more-list-view',
    height: 250,
    id: 'mainMoreSignsAssureListView',
    width: 900,
    collapsible: true,
    header: {
        iconCls: 'x-fa fa-list'
    },
    title: 'Чертежи, на подпись(для заверения)',
    split: true,
    enableColumnHide: false,
    enableColumnMove: false,

    bind: {
        selection: '{current.signAssureFile}',
        store: '{moreSignsAssureStore}'
    },
    columns: [
        {
            xtype: 'gridcolumn',
            flex: 1,
            dataIndex: 'shCh',
            text: 'ШЧ'
        },
        {
            xtype: 'gridcolumn',
            flex: 1,
            dataIndex: 'stnLine',
            text: 'Станция/перегон'
        },
        {
            xtype: 'gridcolumn',
            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                metaData.style = 'white-space:normal;';
                return value;
            },
            flex: 1,
            dataIndex: 'num',
            text: 'Номер'
        },
        {
            xtype: 'gridcolumn',
            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                metaData.style = 'white-space:normal;';
                return value;
            },
            flex: 2,
            dataIndex: 'descr',
            text: 'Наименование'
        },
        {
            xtype: 'gridcolumn',
            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                metaData.style = 'white-space:normal;';
                return value;
            },
            flex: 1,
            dataIndex: 'dateSign',
            text: 'Подписано'
        },
        {
            xtype: 'numbercolumn',
            flex: 1,
            dataIndex: 'signNum',
            text: 'На подпись',
            format: '0'
        },
        {
            xtype: 'gridcolumn',
            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                metaData.style = 'white-space:normal;';
                return value;
            },
            flex: 2,
            dataIndex: 'noteShl',
            text: 'Комментарий',
            bind: {
                hidden: '{isNoteHidden}'
            }
        }
    ],
    listeners: {
        itemdblclick: 'onDocItemDblClick',
        expand: 'onExpand',
        collapse: 'onCollapse',
        float: 'onFloat',
        unfloat: 'onUnfloat'
    },
    dockedItems: [
        {
            xtype: 'pagingtoolbar',
            dock: 'bottom',
            displayInfo: true,
            bind: {
                store: '{moreSignsAssureStore}'
            }
        },
        {
            xtype: 'button',
            dock: 'bottom',
            width: 100,
            iconCls: 'x-fa fa-check',
            text: 'Перейти',
            listeners: {
                click: 'onGoToSelectedDocClick'
            }
        }
    ]

});