/*
 * File: app/view/main/MainView.js
 *
 * This file was generated by Sencha Architect version 4.2.8.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.view.main.MainView', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.main',

    requires: [
        'ASTD.view.main.MainViewModel',
        'ASTD.view.main.MainViewController',
        'ASTD.view.catalog.CatalogListView',
        'Ext.tree.Panel',
        'Ext.Img',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Separator',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.button.Button',
        'Ext.menu.Menu',
        'Ext.menu.Item'
    ],

    controller: 'main.mainview',
    viewModel: {
        type: 'main.mainview'
    },
    reference: 'main',
    layout: 'border',

    items: [
        {
            xtype: 'catalog.cataloglistview',
            reference: 'catalogList',
            region: 'west',
            listeners: {
                clickCatalogList: 'onClickCatalogList',
                loadCurrentUserInfo: 'onLoadCurrentUserInfo'
            }
        },
        {
            xtype: 'container',
            region: 'north',
            id: 'app-header',
            layout: {
                type: 'hbox',
                align: 'middle'
            },
            items: [
                {
                    xtype: 'image',
                    height: 70,
                    id: 'app-header-logo',
                    width: 150,
                    src: './resources/images/logo_bzhd.png'
                },
                {
                    xtype: 'component',
                    flex: 1,
                    html: '<h1>АС «ТД Ш»</h1>',
                    id: 'app-header-text',
                    minWidth: 218
                },
                {
                    xtype: 'container',
                    height: 70,
                    id: 'app-header-right',
                    width: 1100,
                    layout: {
                        type: 'vbox',
                        align: 'right'
                    },
                    items: [
                        {
                            xtype: 'component',
                            id: 'app-header-user',
                            bind: {
                                html: '<h3><label>{current.user.positionName}</label> {current.user.name}</h3>'
                            }
                        },
                        {
                            xtype: 'toolbar',
                            flex: 1,
                            ui: 'footer',
                            items: [
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'radiogroup',
                                    reference: 'headerRadioBranchType',
                                    id: 'app-header-branch-type',
                                    fieldLabel: 'Листы',
                                    labelStyle: 'color: #676767;',
                                    labelWidth: 60,
                                    simpleValue: true,
                                    bind: {
                                        value: '{current.branchType}'
                                    },
                                    listeners: {
                                        change: 'onChangeBranchType'
                                    },
                                    items: [
                                        {
                                            xtype: 'radiofield',
                                            width: 100,
                                            name: 'branchType',
                                            boxLabel: 'В работе',
                                            inputValue: 'DEFAULT',
                                            bind: {
                                                hidden: '{isDefaultRadioHidden}'
                                            }
                                        },
                                        {
                                            xtype: 'radiofield',
                                            width: 130,
                                            name: 'branchType',
                                            boxLabel: 'Утверждено',
                                            inputValue: 'APPROVED',
                                            bind: {
                                                hidden: '{isApprovedRadioHidden}'
                                            }
                                        },
                                        {
                                            xtype: 'radiofield',
                                            name: 'branchType',
                                            boxLabel: 'Архив',
                                            inputValue: 'ARCHIVE',
                                            bind: {
                                                hidden: '{isArchiveRadioHidden}'
                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    style: 'border: 1px solid #333399;',
                                    iconCls: 'x-fa fa-search',
                                    text: 'Поиск',
                                    menu: {
                                        xtype: 'menu',
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                iconCls: 'x-fa fa-drafting-compass',
                                                text: 'Чертежи',
                                                listeners: {
                                                    click: 'onSearchDocsBtnClick'
                                                }
                                            },
                                            {
                                                xtype: 'menuitem',
                                                iconCls: 'x-fa fa-layer-group',
                                                text: 'Листы',
                                                listeners: {
                                                    click: 'onSearchFilesBtnClick'
                                                }
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    style: 'border: 1px solid #333399;',
                                    iconCls: 'x-fa fa-file-signature',
                                    text: 'На подпись',
                                    bind: {
                                        hidden: '{isMoreSignsBtnHidden}'
                                    },
                                    listeners: {
                                        click: 'onMoreSignsBtnClick'
                                    }
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    style: 'border: 1px solid #333399;',
                                    iconCls: 'x-fa fa-marker',
                                    text: 'Заверить',
                                    bind: {
                                        hidden: '{isMoreSignsAssureBtnHidden}'
                                    },
                                    listeners: {
                                        click: 'onMoreSignsAssureBtnClick'
                                    }
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    style: 'border: 1px solid #333399;',
                                    iconCls: 'x-fa fa-stamp',
                                    text: 'Утвержденные',
                                    bind: {
                                        hidden: '{isMoreApprovedBtnHidden}'
                                    },
                                    listeners: {
                                        click: 'onMoreApprovedBtnClick'
                                    }
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    style: 'border: 1px solid #f12222;',
                                    iconCls: 'x-fa fa-ban',
                                    text: 'Отклоненные',
                                    bind: {
                                        hidden: '{isMoreRejectedBtnHidden}'
                                    },
                                    listeners: {
                                        click: 'onMoreRejectedBtnClick'
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});