/*
 * File: app/model/BaseModel.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.model.BaseModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field',
        'Ext.data.identifier.Negative'
    ],

    schema: {
        namespace: 'ASTD.model',
        urlPrefix: './api',
        proxy: {
            type: 'rest',
            url: '{prefix}/{[values.entityName ? values.entityName.substr(0, values.entityName.indexOf("Model")).toLowerCase() : ""]}',
            reader: {
                type: 'json',
                rootProperty: function(data){
                            return data ? data.items || data.children || data.item : {};                 
                        }
            },
            writer: {
                partialDataOptions: {
                    changes: false,
                    associated: true
                }
            }
        }
    },

    fields: [
        {
            allowNull: true,
            name: 'id',
            persist: false
        }
    ],

    identifier: {
        type: 'negative'
    }
});