/*
 * File: app/model/CatalogModel.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.model.CatalogModel', {
    extend: 'ASTD.model.BaseModel',

    requires: [
        'Ext.data.field.String',
        'Ext.data.field.Boolean',
        'Ext.data.field.Integer'
    ],

    validators: {
        name: [
            {
                type: 'presence'
            },
            {
                type: 'length',
                max: 50
            }
        ]
    },

    fields: [
        {
            type: 'string',
            name: 'name'
        },
        {
            type: 'boolean',
            defaultValue: false,
            name: 'readOnly'
        },
        {
            type: 'int',
            name: 'level'
        },
        {
            type: 'string',
            allowNull: true,
            defaultValue: 'DEFAULT',
            name: 'type'
        },
        {
            type: 'int',
            name: 'parentCatalogId',
            reference: {
                type: 'CatalogModel',
                role: 'parentCatalog',
                inverse: 'childCatalogs'
            }
        },
        {
            type: 'int',
            name: 'realId'
        },
        {
            type: 'string',
            allowNull: true,
            defaultValue: 'DEFAULT',
            name: 'branchType'
        },
        {
            type: 'boolean',
            defaultValue: true,
            name: 'isCatalog'
        }
    ]
});