/*
 * File: app/model/DocModel.js
 *
 * This file was generated by Sencha Architect version 4.2.8.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.model.DocModel', {
    extend: 'ASTD.model.BaseModel',

    requires: [
        'Ext.data.field.String',
        'Ext.data.field.Integer',
        'Ext.data.field.Boolean'
    ],

    fields: [
        {
            type: 'string',
            name: 'num'
        },
        {
            type: 'string',
            name: 'noteShl'
        },
        {
            type: 'string',
            name: 'descr'
        },
        {
            type: 'int',
            name: 'catalogId',
            reference: {
                type: 'CatalogModel',
                role: 'catalog',
                inverse: 'docs'
            }
        },
        {
            type: 'int',
            defaultValue: 0,
            name: 'filesNum'
        },
        {
            type: 'boolean',
            defaultValue: false,
            name: 'readOnly'
        },
        {
            type: 'boolean',
            defaultValue: false,
            name: 'archive'
        },
        {
            type: 'boolean',
            defaultValue: false,
            name: 'rejected'
        },
        {
            type: 'int',
            defaultValue: 1,
            name: 'npp'
        },
        {
            type: 'int',
            defaultValue: 0,
            name: 'signNum'
        },
        {
            type: 'int',
            allowNull: true,
            name: 'rootCatalogId'
        }
    ]
});