/*
 * File: app/model/EcpReviewPersonModel.js
 *
 * This file was generated by Sencha Architect version 4.2.8.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.model.EcpReviewPersonModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.String',
        'Ext.data.field.Integer'
    ],

    fields: [
        {
            type: 'string',
            name: 'name'
        },
        {
            type: 'string',
            name: 'position'
        },
        {
            type: 'int',
            name: 'fileId'
        },
        {
            type: 'string',
            name: 'createdDate'
        },
        {
            type: 'string',
            name: 'invalid'
        },
        {
            type: 'string',
            defaultValue: 'Сверено с экземпляром дистанции',
            name: 'status'
        }
    ]
});