/*
 * File: app/model/FileModel.js
 *
 * This file was generated by Sencha Architect version 4.2.8.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.model.FileModel', {
    extend: 'ASTD.model.BaseModel',

    requires: [
        'Ext.data.field.String',
        'Ext.data.field.Integer',
        'Ext.data.field.Boolean',
        'Ext.data.field.Date'
    ],

    fields: [
        {
            type: 'string',
            name: 'name'
        },
        {
            type: 'string',
            name: 'contentType'
        },
        {
            type: 'int',
            name: 'size'
        },
        {
            type: 'int',
            name: 'docId',
            reference: {
                type: 'DocModel',
                role: 'doc',
                inverse: 'files'
            }
        },
        {
            type: 'string',
            name: 'listNum'
        },
        {
            type: 'string',
            name: 'descr'
        },
        {
            type: 'string',
            name: 'noteShl'
        },
        {
            type: 'string',
            name: 'themeShchtd'
        },
        {
            type: 'int',
            name: 'routeId',
            reference: {
                type: 'RouteModel',
                role: 'route',
                inverse: 'files'
            }
        },
        {
            type: 'string',
            defaultValue: 'DEFAULT',
            name: 'status'
        },
        {
            type: 'string',
            allowNull: true,
            defaultValue: 'DEFAULT',
            name: 'branchType'
        },
        {
            type: 'int',
            defaultValue: 0,
            name: 'signedNum'
        },
        {
            type: 'int',
            defaultValue: 0,
            name: 'totalSignsNum'
        },
        {
            type: 'string',
            calculate: function(data) {
                return data.signedNum + '/' + data.totalSignsNum;
            },
            name: 'signs'
        },
        {
            type: 'boolean',
            defaultValue: false,
            name: 'canBeSigned'
        },
        {
            type: 'boolean',
            defaultValue: true,
            name: 'notSignedYet'
        },
        {
            type: 'boolean',
            defaultValue: false,
            name: 'hasPrevVersion'
        },
        {
            type: 'boolean',
            defaultValue: false,
            name: 'hasNextVersion'
        },
        {
            type: 'string',
            name: 'routePositionStatus'
        },
        {
            type: 'boolean',
            defaultValue: false,
            name: 'myOrderToSign'
        },
        {
            type: 'boolean',
            defaultValue: false,
            name: 'myOrderToSignAfterUpdate'
        },
        {
            type: 'boolean',
            defaultValue: false,
            name: 'originalCheckedSigned'
        },
        {
            type: 'int',
            name: 'prevVersionId'
        },
        {
            type: 'int',
            name: 'nextVersionId'
        },
        {
            type: 'int',
            name: 'kbSize'
        },
        {
            type: 'string',
            defaultValue: 'DEFAULT',
            name: 'routeName'
        },
        {
            type: 'boolean',
            defaultValue: false,
            name: 'paperShL'
        },
        {
            type: 'boolean',
            defaultValue: false,
            name: 'paperShChTD'
        },
        {
            type: 'string',
            name: 'statusModifiedBy'
        },
        {
            type: 'string',
            name: 'fioSign1'
        },
        {
            type: 'string',
            name: 'fioSign2'
        },
        {
            type: 'date',
            name: 'dateSign1'
        },
        {
            type: 'date',
            name: 'dateSign2'
        },
        {
            type: 'int',
            name: 'nextSignPositionId'
        },
        {
            type: 'int',
            defaultValue: 0,
            name: 'mySignsNum'
        },
        {
            type: 'int',
            name: 'routePositionId'
        }
    ]
});