/*
 * File: app/model/MoreSignsModel.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.model.MoreSignsModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.String'
    ],

    idProperty: 'docId',

    fields: [
        {
            type: 'int',
            name: 'docId'
        },
        {
            type: 'int',
            name: 'catalogId'
        },
        {
            type: 'int',
            name: 'npp'
        },
        {
            type: 'string',
            name: 'descr'
        },
        {
            type: 'int',
            name: 'signNum'
        },
        {
            type: 'string',
            name: 'shCh'
        },
        {
            type: 'string',
            name: 'stnLine'
        },
        {
            type: 'string',
            name: 'num'
        },
        {
            type: 'string',
            name: 'dateShch'
        }
    ]
});