/*
 * File: app/model/MoreApprovedModel.js
 *
 * This file was generated by Sencha Architect version 4.2.8.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.model.MoreApprovedModel', {
    extend: 'ASTD.model.BaseModel',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.String',
        'Ext.data.field.Boolean'
    ],

    idProperty: 'docId',

    fields: [
        {
            type: 'int',
            name: 'docId'
        },
        {
            type: 'int',
            name: 'catalogId'
        },
        {
            type: 'int',
            name: 'npp'
        },
        {
            type: 'string',
            name: 'shCh'
        },
        {
            type: 'string',
            name: 'stnLine'
        },
        {
            type: 'string',
            name: 'num'
        },
        {
            type: 'string',
            name: 'descr'
        },
        {
            type: 'string',
            name: 'dateSign'
        },
        {
            type: 'int',
            name: 'listCount'
        },
        {
            type: 'boolean',
            defaultValue: false,
            name: 'paperShL'
        },
        {
            type: 'boolean',
            defaultValue: false,
            name: 'paperShChTD'
        }
    ]
});