/*
 * File: app/model/SearchFileModel.js
 *
 * This file was generated by Sencha Architect version 4.2.8.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.model.SearchFileModel', {
    extend: 'ASTD.model.BaseModel',

    requires: [
        'Ext.data.field.String',
        'Ext.data.field.Integer'
    ],

    fields: [
        {
            type: 'string',
            name: 'rootCatalogName'
        },
        {
            type: 'int',
            name: 'docCatalogId'
        },
        {
            type: 'string',
            name: 'docCatalogName'
        },
        {
            type: 'int',
            name: 'docId'
        },
        {
            type: 'int',
            name: 'docNpp'
        },
        {
            type: 'string',
            name: 'docNum'
        },
        {
            type: 'string',
            name: 'docDescr'
        },
        {
            type: 'string',
            name: 'descr'
        },
        {
            type: 'string',
            name: 'branchType'
        },
        {
            type: 'string',
            name: 'status'
        },
        {
            type: 'string',
            name: 'statusText'
        },
        {
            type: 'string',
            name: 'listNum'
        }
    ]
});