/*
 * File: app/model/SearchDocModel.js
 *
 * This file was generated by Sencha Architect version 4.2.8.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.model.SearchDocModel', {
    extend: 'ASTD.model.BaseModel',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.String'
    ],

    fields: [
        {
            type: 'int',
            defaultValue: 1,
            name: 'npp'
        },
        {
            type: 'string',
            name: 'num'
        },
        {
            type: 'string',
            name: 'descr'
        },
        {
            type: 'int',
            name: 'docCatalogId'
        },
        {
            type: 'string',
            name: 'rootCatalogName'
        },
        {
            type: 'string',
            name: 'docCatalogName'
        },
        {
            type: 'int',
            name: 'filesDefaultCount'
        },
        {
            type: 'int',
            name: 'filesApprovedCount'
        },
        {
            type: 'int',
            name: 'filesArchiveCount'
        },
        {
            type: 'int',
            name: 'filesAllCount'
        }
    ]
});