/*
 * File: app/model/UserModel.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.model.UserModel', {
    extend: 'ASTD.model.BaseModel',

    requires: [
        'Ext.data.field.String',
        'Ext.data.field.Date',
        'Ext.data.field.Integer'
    ],

    fields: [
        {
            type: 'string',
            name: 'id',
            persist: true
        },
        {
            type: 'string',
            name: 'prevId',
            persist: true
        },
        {
            type: 'string',
            name: 'name'
        },
        {
            type: 'string',
            name: 'positionName'
        },
        {
            type: 'string',
            name: 'rootCatalogName'
        },
        {
            type: 'string',
            name: 'organization'
        },
        {
            type: 'date',
            name: 'expiredDate',
            dateFormat: 'd.m.Y'
        },
        {
            type: 'int',
            name: 'positionId'
        },
        {
            type: 'int',
            allowNull: true,
            name: 'rootCatalogId'
        }
    ]
});