/*
 * File: app/view/audit/AuditListView.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.view.audit.AuditListView', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.audit.auditlistview',

    requires: [
        'ASTD.view.audit.AuditListViewModel',
        'Ext.grid.column.Number',
        'Ext.view.Table',
        'Ext.toolbar.Paging'
    ],

    viewModel: {
        type: 'audit.auditlistview'
    },
    reference: 'auditList',
    cls: 'my-title',
    glyph: 'xf0ce@FontAwesome',
    title: 'Журнал аудита',
    enableColumnHide: false,
    enableColumnMove: false,
    enableColumnResize: false,
    sortableColumns: false,

    bind: {
        store: '{auditStore}'
    },
    columns: [
        {
            xtype: 'numbercolumn',
            dataIndex: 'entityId',
            text: 'Id',
            format: '0'
        },
        {
            xtype: 'gridcolumn',
            flex: 1,
            dataIndex: 'entityType',
            text: 'Тип'
        },
        {
            xtype: 'gridcolumn',
            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                metaData.style = 'white-space:normal;';
                return value;
            },
            flex: 1,
            dataIndex: 'action',
            text: 'Действие'
        },
        {
            xtype: 'gridcolumn',
            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                metaData.style = 'white-space:normal;';
                return value;
            },
            flex: 5,
            dataIndex: 'entityValue',
            text: 'Данные'
        },
        {
            xtype: 'numbercolumn',
            dataIndex: 'commitVersion',
            text: 'Версия',
            format: '0'
        },
        {
            xtype: 'gridcolumn',
            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                metaData.style = 'white-space:normal;';
                return value;
            },
            dataIndex: 'userName',
            text: 'Кто?'
        },
        {
            xtype: 'gridcolumn',
            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                metaData.style = 'white-space:normal;';
                return value;
            },
            flex: 1,
            dataIndex: 'createdDate',
            text: 'Когда?'
        }
    ],
    viewConfig: {
        loadMask: false
    },
    dockedItems: [
        {
            xtype: 'pagingtoolbar',
            dock: 'bottom',
            displayInfo: true,
            bind: {
                store: '{auditStore}'
            }
        }
    ]

});