/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 4.2.8.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({
    models: [
        'BaseModel',
        'CatalogModel',
        'FileModel',
        'DocModel',
        'RouteModel',
        'EcpPersonModel',
        'UserModel',
        'MoreSignsModel',
        'AuditModel',
        'MoreRejectedModel',
        'PositionModel',
        'MoreSignsAssureModel',
        'MoreApprovedModel',
        'SearchDocModel',
        'SearchFileModel',
        'EcpReviewPersonModel'
    ],
    views: [
        'main.MainView',
        'catalog.CatalogListView',
        'file.FileListView',
        'catalog.CatalogFormView',
        'file.FileFormView',
        'doc.DocListView',
        'doc.DocFormView',
        'file.FileRejectFormView',
        'file.FileEcpPersonsListView',
        'file.FileHistoryFormView',
        'audit.AuditListView',
        'doc.DocDeclineFormView',
        'doc.DocEcpPersonsListView',
        'user.UserListView',
        'user.UserFormView',
        'main.MainMoreApprovedListView',
        'main.MainMoreSignsListView',
        'main.MainMoreRejectedListView',
        'main.MainMoreSignsAssureListView',
        'main.MainSearchDocsListView',
        'main.MainSearchFilesListView',
        'file.FileEcpReviewPersonsListView',
        'file.FileChangeRouteFormView'
    ],
    name: 'ASTD',

    requires: [
        'ASTD.Utils',
        'Ext.data.proxy.*',
        'Ext.window.Toast',
        'ASTD.AdvancedVTypes'
    ],

    launch: function() {
        Ext.create('ASTD.view.main.MainView');
        if(Ext.fly('initialLoader')){
            Ext.fly('initialLoader').destroy();
        }

        Ext.util.Observable.observe(Ext.data.Connection, {
            requestexception: function(conn, response, options) {
                var responseText = '';
                        if (response.responseText) {
                            responseText = Ext.decode(response.responseText);
                        } else if (response.responseJson) {
                            responseText = response.responseJson;
                        }
                        if (!responseText['preventDefault']) {
                            delete options.failure;
                            delete options.callback;
                            Ext.Msg.hide();
                            Ext.Msg.show({
                                title: 'Ошибка',
                                msg: responseText ? responseText.message : response.statusText,
                                buttons: Ext.Msg.OK,
                                icon: Ext.Msg.ERROR
                            });
                        }
            },
            requestcomplete: function(conn, response, options) {
                Ext.Msg.hide();
            },
            timeout: 300000
        });
    }

});
