/*
 * File: app/view/file/FileEcpPersonsListView.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.view.file.FileEcpPersonsListView', {
    extend: 'Ext.window.Window',
    alias: 'widget.file.fileecppersonslistview',

    requires: [
        'ASTD.view.file.FileEcpPersonsListViewModel',
        'ASTD.view.file.FileEcpPersonsListViewController',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.view.Table',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    controller: 'file.fileecppersonslistview',
    viewModel: {
        type: 'file.fileecppersonslistview'
    },
    modal: true,
    width: 800,
    layout: 'fit',
    header: {
        glyph: 'xf0a3@FontAwesome'
    },
    title: 'Подписи',

    items: [
        {
            xtype: 'gridpanel',
            enableColumnHide: false,
            enableColumnMove: false,
            enableColumnResize: false,
            sortableColumns: false,
            bind: {
                store: '{ecpPersonsStore}'
            },
            columns: [
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        metaData.style = 'white-space:normal;';
                        return value;
                    },
                    flex: 4,
                    dataIndex: 'position',
                    text: 'Должность'
                },
                {
                    xtype: 'gridcolumn',
                    flex: 3,
                    dataIndex: 'name',
                    text: 'ФИО'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        metaData.style = 'white-space:normal;';
                        return value;

                    },
                    flex: 2,
                    dataIndex: 'routePositionStatus',
                    text: 'Статус'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        metaData.style = 'white-space:normal;';
                        return value;
                    },
                    flex: 4,
                    dataIndex: 'createdDate',
                    text: 'Дата'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        return value === 'false' ? 'Да' : value === 'true' ? 'Нет' : '';
                    },
                    flex: 2,
                    dataIndex: 'invalid',
                    text: 'Подпись<br/> верна?'
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'bottom',
            ui: 'footer',
            layout: {
                type: 'hbox',
                pack: 'end'
            },
            items: [
                {
                    xtype: 'button',
                    glyph: 'xf057@FontAwesome',
                    text: 'Закрыть',
                    listeners: {
                        click: 'onCloseClick'
                    }
                }
            ]
        }
    ]

});