/*
 * File: app/view/file/FileHistoryFormViewModel.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.view.file.FileHistoryFormViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.file.filehistoryformview',

    requires: [
        'Ext.app.bind.Formula'
    ],

    formulas: {
        breadCrumbs: function(get) {
            var catalog = get('current.catalog');
            if(!catalog || !catalog.parentNode || !catalog.parentNode.parentNode) {
                return '';
            }
            var tcatalog = catalog.parentNode.parentNode.data.name + ' > ' + catalog.parentNode.data.name + ' > ' +
            catalog.data.name  + ' > ';
            var doc = get('current.doc');
            if(!doc) {
                return tcatalog;
            }
            return tcatalog + '<span>' + doc.data.num + '&nbsp;&nbsp;&nbsp;' + doc.data.descr  + ' ></span> ';
        },
        isSavePaperBtnHidden: function(get) {
            var file = get('prevFileVersion');
            if(!file) {
                return false;
            }
            return file.get('branchType') === 'ARCHIVE';
        },
        glyphPaperShL: function(get) {
            var file = get('prevFileVersion');
            if(!file) {
                return '';
            }
            return (file.get('paperShL') ? "<span style=\"font: 20px/0.7 FontAwesome;\">&#61638;</span>" : "");
        },
        glyphPaperShChTD: function(get) {
            var file = get('prevFileVersion');
            if(!file) {
                return '';
            }
            return (file.get('paperShChTD') ? "<span style=\"font: 20px/0.7 FontAwesome;\">&#61638;</span>" : "");
        },
        getEmbedFileHtml: function(get) {
            var file = get('prevFileVersion');
            if(!file) {
                return '';
            }
            return file.get('contentType').indexOf('/pdf') !== -1 ?
            '<embed src="' + file.getProxy().getUrl() + '/view/' + file.getId() +  '" width="100%" height="600">' :
            '<b>Просмотр доступен только для pdf</b>';
        },
        isPrevVersionBtnHidden: {
            get: function(data) {
                var isHidden = false;
                var file = data;
                if(!file) {
                    return true;
                }
                isHidden = !file.get('hasPrevVersion');
                return isHidden;
            },
            bind: {
                bindTo: '{prevFileVersion}',
                deep: true
            }
        },
        isNextVersionBtnHidden: {
            get: function(data) {
                var isHidden = false;
                var file = data;
                if(!file) {
                    return true;
                }
                isHidden = !file.get('hasNextVersion');
                return isHidden;
            },
            bind: {
                bindTo: '{prevFileVersion}',
                deep: true
            }
        },
        isSignBtnHidden: {
            get: function(data) {
                var file = data;
                isHidden = !file.get('myOrderToSign') ||
                file.get('status') === 'APPROVED' || file.get('status') === 'REFERENCE' || file.get('status') === 'DAMAGED' || file.get('status') === 'INVALID' ||
                file.get('status') === 'REJECTED';


                return isHidden;
            },
            bind: {
                bindTo: '{prevFileVersion}',
                deep: true
            }
        },
        isNewVersionBtnHidden: {
            get: function(data) {
                var isHidden = false;
                var file = data;
                var user = this.get('current.user');
                if (!file || !user) {
                    return true;
                }
                isHidden =
                (file.get('status') !== 'APPROVED' && file.get('status') !== 'REFERENCE' && file.get('status') !== 'REJECTED') ||
                file.get('hasNextVersion') ||
                (user.get('positionId') !== 9 && user.get('positionId') !== 5);

                if(!isHidden){
                    isHidden =  file.get('routePositionId') !== user.get('positionId');
                }
                return isHidden;
            },
            bind: {
                bindTo: '{prevFileVersion}',
                deep: true
            }
        },
        isRejectBtnHidden: {
            get: function(data) {
                var file = data;
                isHidden = !file.get('myOrderToSign') ||
                file.get('status') === 'APPROVED' || file.get('status') === 'REFERENCE' || file.get('status') === 'DAMAGED' || file.get('status') === 'INVALID' ||
                file.get('status') === 'REJECTED';


                return isHidden;
            },
            bind: {
                bindTo: '{prevFileVersion}',
                deep: true
            }
        },
        isRejectCancelBtnHidden: {
            get: function(data) {
                var file = data;
                var user = this.get('current.user');
                return file.get('status') !== 'REJECTED' || file.get('hasNextVersion') || file.get('statusModifiedBy') !== user.getId();
            },
            bind: {
                bindTo: '{prevFileVersion}',
                deep: true
            }
        }
    }

});