/*
 * File: app/view/file/FileRejectFormView.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.view.file.FileRejectFormView', {
    extend: 'Ext.window.Window',
    alias: 'widget.file.filerejectformview',

    requires: [
        'ASTD.view.file.FileRejectFormViewModel',
        'ASTD.view.file.FileRejectFormViewController',
        'Ext.form.Panel',
        'Ext.form.field.TextArea',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    controller: 'file.filerejectformview',
    viewModel: {
        type: 'file.filerejectformview'
    },
    modal: true,
    id: 'fileRejectFormViewController',
    width: 600,
    layout: 'fit',
    header: {
        glyph: 'xf075@FontAwesome'
    },
    title: 'Отклонить',

    items: [
        {
            xtype: 'form',
            reference: 'docRejectForm',
            modelValidation: true,
            bodyPadding: 10,
            header: false,
            items: [
                {
                    xtype: 'textareafield',
                    anchor: '100%',
                    fieldLabel: 'Причина отказа',
                    allowBlank: false,
                    bind: {
                        value: '{msg}'
                    }
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'bottom',
            ui: 'footer',
            layout: {
                type: 'hbox',
                pack: 'end'
            },
            items: [
                {
                    xtype: 'button',
                    glyph: 'xf0c7@FontAwesome',
                    text: 'Сохранить',
                    listeners: {
                        click: 'onSaveClick'
                    }
                },
                {
                    xtype: 'button',
                    glyph: 'xf057@FontAwesome',
                    text: 'Отменить',
                    listeners: {
                        click: 'onCancelClick'
                    }
                }
            ]
        }
    ]

});