/*
 * File: app/view/file/FileFormView.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.view.file.FileFormView', {
    extend: 'Ext.window.Window',
    alias: 'widget.file.fileformview',

    requires: [
        'ASTD.view.file.FileFormViewModel',
        'ASTD.view.file.FileFormViewController',
        'Ext.form.Panel',
        'Ext.form.field.File',
        'Ext.form.field.ComboBox',
        'Ext.form.field.TextArea',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.form.field.Hidden'
    ],

    controller: 'file.fileformview',
    viewModel: {
        type: 'file.fileformview'
    },
    modal: true,
    width: 600,
    layout: 'fit',
    header: {
        glyph: 'xf044@FontAwesome'
    },
    title: 'Лист',

    items: [
        {
            xtype: 'form',
            reference: 'fileForm',
            modelValidation: true,
            bodyPadding: 10,
            header: false,
            items: [
                {
                    xtype: 'filefield',
                    anchor: '100%',
                    fieldLabel: 'Лист',
                    name: 'file',
                    allowBlank: false,
                    buttonText: 'Выбрать...'
                },
                {
                    xtype: 'combobox',
                    anchor: '100%',
                    fieldLabel: 'Маршрут',
                    name: 'routeId',
                    editable: false,
                    displayField: 'name',
                    forceSelection: true,
                    queryMode: 'local',
                    valueField: 'id',
                    bind: {
                        value: '{currentFile.routeId}',
                        store: '{routeStore}'
                    }
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: '№ Листа',
                    name: 'listNum',
                    bind: {
                        value: '{currentFile.listNum}'
                    }
                },
                {
                    xtype: 'textareafield',
                    anchor: '100%',
                    fieldLabel: 'Наименование',
                    name: 'descr',
                    bind: {
                        value: '{currentFile.descr}'
                    }
                },
                {
                    xtype: 'hiddenfield',
                    name: 'docId',
                    bind: {
                        value: '{currentFile.docId}'
                    }
                },
                {
                    xtype: 'hiddenfield',
                    name: 'id',
                    bind: {
                        value: '{currentFile.id}'
                    }
                },
                {
                    xtype: 'hiddenfield',
                    name: 'status',
                    bind: {
                        value: '{currentFile.status}'
                    }
                },
                {
                    xtype: 'hiddenfield',
                    name: 'branchType',
                    bind: {
                        value: '{currentFile.branchType}'
                    }
                },
                {
                    xtype: 'hiddenfield',
                    name: 'nextSignPositionId',
                    bind: {
                        value: '{currentFile.nextSignPositionId}'
                    }
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    ui: 'footer',
                    layout: {
                        type: 'hbox',
                        pack: 'end'
                    },
                    items: [
                        {
                            xtype: 'button',
                            glyph: 'xf0c7@FontAwesome',
                            text: 'Сохранить',
                            listeners: {
                                click: 'onSaveClick'
                            }
                        },
                        {
                            xtype: 'button',
                            glyph: 'xf057@FontAwesome',
                            text: 'Отменить',
                            listeners: {
                                click: 'onCancelClick'
                            }
                        }
                    ]
                }
            ]
        }
    ]

});