/*
 * File: app/view/file/FileChangeRouteFormViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.8.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.view.file.FileChangeRouteFormViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.file.filechangerouteformview',

    onComplete: function(options, success, response) {
        Ext.Msg.hide();
        Ext.toast({
            title: 'Отклонение',
            html: success ? 'Данные успешно сохранены' : 'Ошибка',
            align: 'tr',
            bodyPadding: 10
        });
        this.getView().close();
    },

    onSaveClick: function(button, e, eOpts) {
        var form = this.lookupReference('changeRouteForm');

        if (form.isValid()) {
            Ext.Msg.wait('Сохранение', 'Сохранение данных...');

            var currentFile = this.getViewModel().get('currentFile');
            var routeId = this.lookupReference('routes').getValue();
            Ext.Ajax.request({
                url: currentFile.getProxy().getUrl() + '/change-route/' + currentFile.getId() + '/' + routeId,
                method: 'POST',
                scope: this,
                callback: this.onComplete
            });
        }
    },

    onCancelClick: function(button, e, eOpts) {
        this.getView().close();
    }

});
