/*
 * File: app/view/file/FileHistoryFormViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.view.file.FileHistoryFormViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.file.filehistoryformview',

    id: 'fileHistoryFormViewController',

    onSaveEcp: function(ecp) {
        var currentFile = this.getViewModel().get('prevFileVersion');
        Ext.Msg.wait('Подпись', 'Сохранение данных...');
        Ext.Ajax.request({
            url: currentFile.getProxy().getUrl() + '/ecp/' + currentFile.getId(),
            method: 'POST',
            params: {ecp: ecp},
            scope: this,
            callback: function(options, success, response) {
                Ext.Msg.hide();
                var responseText = Ext.decode(response.responseText);
                if(responseText.success){
                    Ext.toast({
                        title: 'Подпись',
                        html: 'Подпись успешно сохранена',
                        align: 'tr',
                        bodyPadding: 10
                    });
                    // Ext.Msg.wait("Загрузка", "Загрузка формы");
                    this.fireEvent('clickFileHistoryBtn', this.getView(),
                                   this.getViewModel().get('prevFileVersion'), this.getViewModel().get('prevFileVersion').get('id'));
                    // this.getView().getStore().reload();
                } else {
                    Ext.Msg.show({
                        title: 'Ошибка',
                        msg: responseText ? responseText.message : response.statusText,
                        buttons: Ext.Msg.OK,
                        icon: Ext.Msg.ERROR,
                        scope: this,
                        fn: function(btn) {
                            if(btn === 'ok') {
                              //  Ext.Msg.wait("Загрузка", "Загрузка формы");
                                this.fireEvent('clickFileHistoryBtn', this.getView(),
                                               this.getViewModel().get('prevFileVersion'), this.getViewModel().get('prevFileVersion').get('id'));
                                // this.getView().getStore().reload();
                            }
                        }
                    });
                }
            }
        });
    },

    onSavePaper: function(checkbox) {
        Ext.Msg.show({
            title:'Изменить?',
            message: 'Вы действительно хотите сохранить изменения?',
            buttons: Ext.Msg.YESNO,
            icon: Ext.Msg.QUESTION,
            scope: this,
            fn: function(btn) {
                if(btn === 'yes') {
                    Ext.Msg.wait('Сохранение', 'Сохранение изменений...');
                    var currentFile = this.getViewModel().get('prevFileVersion');
                    Ext.Ajax.request({
                        url: currentFile.getProxy().getUrl() + '/paper/' + currentFile.getId(),
                        method: 'POST',
                        params: {value: checkbox.getValue(), field: checkbox.getReference()},
                        scope: this,
                        callback: function(options, success, response) {
                            Ext.Msg.hide();
                            var responseText = Ext.decode(response.responseText);
                            Ext.toast({
                                title: 'Изменения',
                                html: success ? 'Изменения успешно сохранены' : 'Ошибка',
                                align: 'tr',
                                bodyPadding: 10
                            });
                        }
                    });
                }
            }
        });
    },

    onSavePaperShLBtnClick: function(button, e, eOpts) {
        this.onSavePaper(this.lookup('paperShL'));
    },

    onSavePaperShChTDBtnClick: function(button, e, eOpts) {
        this.onSavePaper(this.lookup('paperShChTD'));
    },

    onViewEcpPersonsBtnClick: function(button, e, eOpts) {
        this.fireEvent('viewEcpPersonsBtnClick', this.getView(), this.getViewModel().get('prevFileVersion'));
    },

    onBackToFilesBtnClick: function(button, e, eOpts) {
        var fileHistoryForm = this.getView();
        this.fireEvent('clickDocList', fileHistoryForm, this.getViewModel().get('current.doc'));
        // this.getViewModel().getParent().getView().getController().onClickDocList(fileHistoryForm, this.getViewModel().get('current.doc'));
        // catalogList.fireEvent('clickDocList', fileHistoryForm, this.getViewModel().get('current.doc'));
    },

    onPrevVersionBtnClick: function(button, e, eOpts) {
        this.fireEvent('clickFileHistoryBtn', this.getView(),
        this.getViewModel().get('prevFileVersion'), this.getViewModel().get('prevFileVersion').get('prevVersionId'));
    },

    onNextVersionBtnClick: function(button, e, eOpts) {
        this.fireEvent('clickFileHistoryBtn', this.getView(),
        this.getViewModel().get('prevFileVersion'), this.getViewModel().get('prevFileVersion').get('nextVersionId'));
    },

    onNewVersionBtnClick: function(button, e, eOpts) {
        var currentFile = this.getViewModel().get('prevFileVersion');
        // currentDoc.data;
        // this.editBtnClick(currentDoc);

        var win = new ASTD.view.file.FileFormView({
            viewModel: {
                data: {
                    currentFile: currentFile,
                    fileHistoryForm: this.getView()
                }
            }
        });

        win.show();
    },

    onViewBtnClick: function(button, e, eOpts) {
        this.fireEvent('viewFileBtnClick', this.getViewModel().get('prevFileVersion'));
    },

    onDownloadBtnClick: function(button, e, eOpts) {
        this.fireEvent('downloadFileBtnClick', this.getViewModel().get('prevFileVersion'));
    },

    onSignBtnClick: function(button, e, eOpts) {
        var currentFile = this.getViewModel().get('prevFileVersion');
        // if(!ASTD.Utils.isSelected(currentFile)){
        //     return false;
        // }

        Ext.Msg.show({
            title: currentFile.get('routePositionStatus'),
            message: 'Вы действительно хотите подписать?',
            buttons: Ext.Msg.YESNO,
            icon: Ext.Msg.QUESTION,
            scope: this,
            fn: function(btn) {
                if(btn === 'yes') {
                    Ext.Msg.wait('Подпись', 'Получение данных...');
                    Ext.Ajax.request({
                        url: currentFile.getProxy().getUrl() + '/ecp',
                        method: 'GET',
                        params: {id: currentFile.getId()},
                        scope: this,
                        callback: function(options, success, response) {
                            Ext.Msg.hide();
                            var responseText = Ext.decode(response.responseText);
                            if(responseText.success){
                                var data = responseText.item;
                                f_checkAndSign(3000, 'certserial:' + data.serial, Ext.encode(data.signData), this.onSaveEcp.bind(this));
                            } else {
                                Ext.Msg.show({
                                    title: 'Ошибка',
                                    msg: responseText ? responseText.message : response.statusText,
                                    buttons: Ext.Msg.OK,
                                    icon: Ext.Msg.ERROR,
                                    scope: this,
                                    fn: function(btn) {
                                        if(btn === 'ok') {
                                            // Ext.Msg.wait("Загрузка", "Загрузка формы");
                                            this.fireEvent('clickFileHistoryBtn', this.getView(),
                                            this.getViewModel().get('prevFileVersion'), this.getViewModel().get('prevFileVersion').get('id'));
                                            // this.getView().getStore().reload();
                                        }
                                    }
                                });
                            }
                        }
                    });
                }
            }
        });
    },

    onRejectBtnClick: function(button, e, eOpts) {
        var currentFile = this.getViewModel().get('prevFileVersion');
        var win = new ASTD.view.file.FileRejectFormView({
            viewModel: {
                data: {
                    currentFile: currentFile,
                    fileHistoryForm: this.getView()
                }
            }
        });

        win.show();
    },

    onRejectCancelBtnClick: function(button, e, eOpts) {
        Ext.Msg.wait('Сохранение', 'Сохранение изменений...');
        var currentFile = this.getViewModel().get('prevFileVersion');
        Ext.Ajax.request({
            url: currentFile.getProxy().getUrl() + '/reject/cancel/' + currentFile.getId(),
            method: 'POST',
            scope: this,
            callback: function(options, success, response) {
                Ext.Msg.hide();
                Ext.toast({
                    title: 'Изменения',
                    html: success ? 'Изменения успешно сохранены' : 'Ошибка',
                    align: 'tr',
                    bodyPadding: 10
                });
                this.fireEvent('clickFileHistoryBtn', this.getView(),
                this.getViewModel().get('prevFileVersion'), this.getViewModel().get('prevFileVersion').get('id'));
            }
        });
    }

});
