/*
 * File: app/view/file/FileFormViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.8.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.view.file.FileFormViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.file.fileformview',

    id: 'fileFormViewController',

    onSuccess: function(form, auditAction) {
        Ext.Msg.hide();
        Ext.toast({
            title: 'Сохранение',
            html: 'Лист успешно сохранен',
            align: 'tr',
            bodyPadding: 10
        });
        if(this.getViewModel().get('fileList')) {
            Ext.Msg.wait("Загрузка", "Загрузка списка");
            this.getViewModel().get('fileList').getStore().reload();
        }
        else {
           // Ext.Msg.wait("Загрузка", "Загрузка формы");
            this.fireEvent('clickFileHistoryBtn', this.getViewModel().get('fileHistoryForm'),
                           this.getViewModel().get('currentFile'),
                           auditAction.result.items[0].id);
        }
        this.getView().close();
    },

    onFailure: function(form, auditAction) {
        Ext.Msg.hide();
        var message = auditAction.result.message ? auditAction.result.message : auditAction.result.items;
        Ext.toast({
            title: 'Сохранение',
            html: 'Ошибка: ' + message,
            align: 'tr',
            bodyPadding: 10
        });
    },

    saveForm: function(form) {
        var rec = this.getViewModel().get('currentFile');
        Ext.Msg.wait('Сохранение', 'Сохранение файла...');
        form.submit({
            url: rec.getProxy().getUrl(),
            scope: this,
            success: this.onSuccess,
            failure: this.onFailure
        });
    },

    onSaveClick: function(button, e, eOpts) {
        var form = this.lookupReference('fileForm');

        if (form.isValid()) {
            var fileField = this.lookupReference('fileField');
            var fileSize = fileField.fileInputEl.dom.files[0].size;
            if (fileSize > (5 * 1024 * 1024)) { // 5MB
                Ext.Msg.show({
                    title:'Предупреждение',
                    message: 'Загружаемый файл больше 5MB, продолжить?',
                    buttons: Ext.Msg.YESNO,
                    icon: Ext.Msg.QUESTION,
                    scope: this,
                    fn: function(btn) {
                        if (btn === 'yes') {
                            this.saveForm(form);
                        }
                    }
                });
            } else {
                this.saveForm(form);
            }

        }
    },

    onCancelClick: function(button, e, eOpts) {
        this.getViewModel().get('currentFile').reject();
        this.getView().close();
    }

});
