/*
 * File: app/view/file/FileListView.js
 *
 * This file was generated by Sencha Architect version 4.2.8.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.view.file.FileListView', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.file.filelistview',

    requires: [
        'ASTD.view.file.FileListViewModel',
        'ASTD.view.file.FileListViewController',
        'Ext.grid.column.Boolean',
        'Ext.grid.column.Widget',
        'Ext.button.Button',
        'Ext.view.Table',
        'Ext.toolbar.Paging'
    ],

    controller: 'file.filelistview',
    viewModel: {
        type: 'file.filelistview'
    },
    reference: 'fileList',
    cls: 'my-title',
    id: 'idFileListView',
    iconCls: 'x-fa fa-file-table',
    enableColumnHide: false,
    enableColumnMove: false,

    bind: {
        title: '{breadCrumbs}Листы &nbsp;&nbsp;&nbsp;[{current.branchTypeText}]',
        selection: '{current.file}',
        store: '{fileStore}'
    },
    columns: [
        {
            xtype: 'booleancolumn',
            style: 'font: 23px/2 FontAwesome;',
            width: 40,
            sortable: false,
            dataIndex: 'paperShL',
            tdCls: 'glyph_01',
            text: '&#128206;',
            falseText: ' ',
            trueText: '&#128206;',
            bind: {
                hidden: '{current.user.positionId !== 5}'
            }
        },
        {
            xtype: 'booleancolumn',
            style: 'font: 23px/2 FontAwesome;',
            width: 40,
            sortable: false,
            dataIndex: 'paperShChTD',
            tdCls: 'glyph_01',
            text: '&#128206;',
            falseText: ' ',
            trueText: '&#128206;',
            bind: {
                hidden: '{current.user.positionId !== 9}'
            }
        },
        {
            xtype: 'gridcolumn',
            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                metaData.style = 'white-space:normal;';
                return value;
            },
            width: 150,
            dataIndex: 'id',
            text: 'Индивидуальный <br/>номер'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'listNum',
            text: 'Лист'
        },
        {
            xtype: 'gridcolumn',
            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                metaData.style = 'white-space:normal;';
                return value;
            },
            flex: 1,
            dataIndex: 'descr',
            text: 'Наименование'
        },
        {
            xtype: 'gridcolumn',
            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                var status = record.get('status');
                metaData.tdCls =
                (status === 'DEFAULT' || status === 'SIGNING') && record.get('myOrderToSign') ?
                'my-next-sign' :
                'status-' + status.toLowerCase();

                return value;
            },
            width: 132,
            sortable: false,
            dataIndex: 'statusText',
            tdCls: 'status_01',
            text: 'Статус'
        },
        {
            xtype: 'widgetcolumn',
            dataIndex: 'signs',
            text: 'Подписи',
            widget: {
                xtype: 'button',
                listeners: {
                    click: 'onViewEcpPersonsBtnClick'
                }
            }
        }
    ],
    viewConfig: {
        loadMask: false
    },
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            overflowHandler: 'scroller',
            items: [
                {
                    xtype: 'button',
                    iconCls: 'x-fa fa-arrow-left',
                    text: 'Назад',
                    listeners: {
                        click: 'onBackToDocsBtnClick'
                    }
                },
                {
                    xtype: 'button',
                    iconCls: 'x-fa fa-upload',
                    text: 'Загрузить',
                    bind: {
                        hidden: '{isUploadBtnHidden}'
                    },
                    listeners: {
                        click: 'onUploadBtnClick'
                    }
                },
                {
                    xtype: 'button',
                    iconCls: 'x-fa fa-edit',
                    text: 'Редактировать',
                    bind: {
                        hidden: '{isEditBtnHidden}'
                    },
                    listeners: {
                        click: 'onEditBtnClick'
                    }
                },
                {
                    xtype: 'button',
                    iconCls: 'x-fa fa-eye',
                    text: 'Просмотреть',
                    listeners: {
                        click: 'onViewBtnClick'
                    }
                },
                {
                    xtype: 'button',
                    iconCls: 'x-fa fa-download',
                    text: 'Выгрузить',
                    listeners: {
                        click: 'onDownloadBtnClick'
                    }
                },
                {
                    xtype: 'button',
                    iconCls: 'x-fa fa-trash',
                    text: 'Удалить',
                    bind: {
                        hidden: '{isDeleteBtnHidden}'
                    },
                    listeners: {
                        click: 'onDeleteBtnClick'
                    }
                },
                {
                    xtype: 'button',
                    iconCls: 'x-fa fa-file-archive',
                    text: 'Архив',
                    bind: {
                        hidden: '{isArchiveBtnHidden}'
                    },
                    listeners: {
                        click: 'onArchiveBtnClick'
                    }
                },
                {
                    xtype: 'button',
                    iconCls: 'x-fa fa-undo',
                    text: 'Отменить архивирование',
                    bind: {
                        hidden: '{isArchiveCancelBtnHidden}'
                    },
                    listeners: {
                        click: 'onArchiveCancelBtnClick'
                    }
                },
                {
                    xtype: 'button',
                    iconCls: 'x-fa fa-file-pdf',
                    text: 'Свойства',
                    listeners: {
                        click: 'onHistoryBtnClick'
                    }
                }
            ]
        },
        {
            xtype: 'pagingtoolbar',
            dock: 'bottom',
            displayInfo: true,
            bind: {
                store: '{fileStore}'
            }
        }
    ],
    listeners: {
        itemdblclick: 'onFileItemDblClick'
    }

});