/*
 * File: app/view/file/FileChangeRouteFormView.js
 *
 * This file was generated by Sencha Architect version 4.2.8.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.view.file.FileChangeRouteFormView', {
    extend: 'Ext.window.Window',
    alias: 'widget.file.filechangerouteformview',

    requires: [
        'ASTD.view.file.FileChangeRouteFormViewModel',
        'ASTD.view.file.FileChangeRouteFormViewController',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    controller: 'file.filechangerouteformview',
    viewModel: {
        type: 'file.filechangerouteformview'
    },
    modal: true,
    width: 600,
    layout: 'fit',
    header: {
        iconCls: 'x-fa fa-comment'
    },
    title: 'Смена маршрута',

    items: [
        {
            xtype: 'form',
            reference: 'changeRouteForm',
            modelValidation: true,
            bodyPadding: 10,
            header: false,
            items: [
                {
                    xtype: 'combobox',
                    anchor: '100%',
                    reference: 'routes',
                    fieldLabel: 'Маршрут',
                    name: 'routeId',
                    allowBlank: false,
                    editable: false,
                    displayField: 'name',
                    forceSelection: true,
                    queryMode: 'local',
                    valueField: 'id',
                    bind: {
                        store: '{routeStore}'
                    }
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'bottom',
            ui: 'footer',
            layout: {
                type: 'hbox',
                pack: 'end'
            },
            items: [
                {
                    xtype: 'button',
                    iconCls: 'x-fa fa-save',
                    text: 'Сохранить',
                    listeners: {
                        click: 'onSaveClick'
                    }
                },
                {
                    xtype: 'button',
                    iconCls: 'x-fa fa-times',
                    text: 'Отменить',
                    listeners: {
                        click: 'onCancelClick'
                    }
                }
            ]
        }
    ]

});