/*
 * File: app/view/file/FileListViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.view.file.FileListViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.file.filelistview',

    id: 'fileListViewController',

    onCompleteDelete: function(record, operation, success) {
        Ext.Msg.hide();
        if(success){
            Ext.Msg.wait("Загрузка", "Загрузка списка");
            this.getView().getStore().reload();
        } else {
            record.dropped = false;
        }
        Ext.toast({
            title: 'Удаление',
            html: success ? 'Файл успешно удален' : 'Ошибка',
            align: 'tr',
            bodyPadding: 10
        });
    },

    editBtnClick: function(currentFile) {
        var win = new ASTD.view.file.FileFormView({
            viewModel: {
                data: {
                    currentFile: currentFile,
                    fileList: this.getView()
                }
            }
        });

        win.show();
    },

    onViewEcpPersonsBtnClick: function(button, e, eOpts) {
        var rec = button.getWidgetRecord();
        this.fireEvent('viewEcpPersonsBtnClick', this.getView(), rec);
        /* var win = new ASTD.view.file.FileEcpPersonsListView({
        viewModel: {
        stores: {
        ecpPersonsStore: rec.ecpPersons()
        }
        }
        });

        win.show(); */
    },

    onBackToDocsBtnClick: function(button, e, eOpts) {
        // var catalogList = this.getView().up('viewport').child('treepanel');
        var catalogList = this.getViewModel().getParent().getView().lookupReference('catalogList');
        catalogList.fireEvent('clickCatalogList', catalogList, this.getViewModel().get('current.catalog'));
    },

    onUploadBtnClick: function(button, e, eOpts) {
        var currentFile = Ext.create('ASTD.model.FileModel', {
            docId:  this.getViewModel().get('docId')
        });
        this.editBtnClick(currentFile);
    },

    onEditBtnClick: function(button, e, eOpts) {
        var currentFile = this.getView().getSelection()[0];
        if(!ASTD.Utils.isSelected(currentFile)){
            return false;
        }
        this.editBtnClick(currentFile);
    },

    onViewBtnClick: function(button, e, eOpts) {
        //this.getFileBtnClick('/view/');
        var currentFile = this.getView().getSelection()[0];
        if(!ASTD.Utils.isSelected(currentFile)){
            return false;
        }
        this.fireEvent('viewFileBtnClick', currentFile);
        // this.onView(currentFile);
    },

    onDownloadBtnClick: function(button, e, eOpts) {
        //this.getFileBtnClick('/download/');
        var currentFile = this.getView().getSelection()[0];
        if(!ASTD.Utils.isSelected(currentFile)){
            return false;
        }

        if(Ext.fly('downloadIframe')){
            Ext.fly('downloadIframe').destroy();
        }

        this.fireEvent('downloadFileBtnClick', currentFile);

        /*Ext.DomHelper.append(document.body, {
        tag: 'iframe',
        id:'downloadIframe',
        frameBorder: 0,
        width: 0,
        height: 0,
        css: 'display:none; visibility:hidden; height:0px; width:0px;',
        src: currentFile.getProxy().getUrl() + '/download/' + currentFile.getId()
        }); */
    },

    onDeleteBtnClick: function(button, e, eOpts) {
        var currentFile = this.getView().getSelection()[0];
        if(!ASTD.Utils.isSelected(currentFile)){
            return false;
        }
        Ext.Msg.show({
            title:'Удалить?',
            message: 'Вы действительно хотите удалить?',
            buttons: Ext.Msg.YESNO,
            icon: Ext.Msg.QUESTION,
            scope: this,
            fn: function(btn) {
                if(btn === 'yes') {
                    Ext.Msg.wait('Удаление', 'Удаление файла...');
                    currentFile.dropped = true;
                    currentFile.save({
                        scope: this,
                        callback: this.onCompleteDelete
                    });
                }
            }
        });
    },

    onArchiveBtnClick: function(button, e, eOpts) {

        if(!ASTD.Utils.isSelected(this.getView().getSelection()[0])){
            return false;
        }

        Ext.Msg.show({
            title:'Архивировать?',
            message: 'Вы действительно хотите архивировать?',
            buttons: [
            {text: 'Yes', itemId: 'yes'},
            // {text: 'OK',     itemId: 'ok'},
            {text: 'Cancel',    itemId: 'cancel'}
            ],
            buttonText:{
                yes: "Да",
                //   ok: "С копией",
                no: "Отмена"
            },
            icon: Ext.Msg.QUESTION,
            scope: this,
            fn: function(btn) {
                if(btn === 'yes' || btn === 'ok') {
                    var currentFile = this.getView().getSelection()[0];
                    Ext.Msg.wait('Архивирование', 'Архивирование данных...');
                    Ext.Ajax.request({
                        url: currentFile.getProxy().getUrl() + '/archive/' + currentFile.getId(),
                        method: 'POST',
                        //    params: {withCopy: btn === 'ok'},
                        scope: this,
                        callback: function(record, operation, success){
                            Ext.Msg.hide();
                            if(success){
                                Ext.Msg.wait("Загрузка списка");
                                this.getView().getStore().reload();
                            }

                            Ext.toast({
                                title: 'Архивирование',
                                html: success ? 'Данные успешно сохранены' : 'Ошибка',
                                align: 'tr',
                                bodyPadding: 10
                            });

                        }
                    });
                }
            }
        });

    },

    onArchiveCancelBtnClick: function(button, e, eOpts) {
        if(!ASTD.Utils.isSelected(this.getView().getSelection()[0])){
            return false;
        }

        Ext.Msg.show({
            title:'Архивировать?',
            message: 'Вы действительно хотите отменить?',
            buttons: [
            {text: 'Yes', itemId: 'yes'},
            // {text: 'OK',     itemId: 'ok'},
            {text: 'Cancel',    itemId: 'cancel'}
            ],
            buttonText:{
                yes: "Да",
                //   ok: "С копией",
                no: "Отмена"
            },
            icon: Ext.Msg.QUESTION,
            scope: this,
            fn: function(btn) {
                if(btn === 'yes' || btn === 'ok') {
                    var currentFile = this.getView().getSelection()[0];
                    Ext.Msg.wait('Отмена', 'Отмена архивирования...');
                    Ext.Ajax.request({
                        url: currentFile.getProxy().getUrl() + '/archive/cancel/' + currentFile.getId(),
                        method: 'POST',
                        //    params: {withCopy: btn === 'ok'},
                        scope: this,
                        callback: function(record, operation, success){
                            Ext.Msg.hide();

                            Ext.toast({
                                title: 'Архивирование',
                                html: success ? 'Данные успешно сохранены' : 'Ошибка',
                                align: 'tr',
                                bodyPadding: 10
                            });

                            if(success){
                                Ext.Msg.wait("Загрузка списка");
                                this.getView().getStore().reload();
                            }

                        }
                    });
                }
            }
        });
    },

    onHistoryBtnClick: function(button, e, eOpts) {
        if(!ASTD.Utils.isSelected(this.getView().getSelection()[0])){
            return false;
        }
        this.fireViewEvent('clickFileHistoryBtn', this.getView(),
        this.getView().getSelection()[0], this.getView().getSelection()[0].get('id'));
    },

    onFileItemDblClick: function(dataview, record, item, index, e, eOpts) {
        this.fireViewEvent('clickFileHistoryBtn', this.getView(),
        this.getView().getSelection()[0], this.getView().getSelection()[0].get('id'));
    }

});
