/*
 * File: app/view/file/FileHistoryFormView.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.view.file.FileHistoryFormView', {
    extend: 'Ext.form.Panel',
    alias: 'widget.file.filehistoryformview',

    requires: [
        'ASTD.view.file.FileHistoryFormViewModel',
        'ASTD.view.file.FileHistoryFormViewController',
        'Ext.form.FieldContainer',
        'Ext.form.field.Checkbox',
        'Ext.button.Button',
        'Ext.form.field.Display',
        'Ext.form.field.Date',
        'Ext.form.field.TextArea',
        'Ext.toolbar.Toolbar'
    ],

    controller: 'file.filehistoryformview',
    viewModel: {
        type: 'file.filehistoryformview'
    },
    reference: 'fileHistoryForm',
    cls: 'my-title detailForm01',
    defaults: {
        labelWidth: 150,
        cls: 'labelField01'
    },
    bodyPadding: 10,
    glyph: 'xf1c1@FontAwesome',

    bind: {
        title: '{breadCrumbs}Лист {prevFileVersion.listNum}&nbsp;&nbsp;&nbsp;[{prevFileVersion.branchTypeText}]'
    },
    items: [
        {
            xtype: 'fieldcontainer',
            anchor: '100%',
            layout: 'hbox',
            fieldLabel: 'Бумага',
            bind: {
                hidden: '{current.user.positionId !== 5}'
            },
            items: [
                {
                    xtype: 'checkboxfield',
                    reference: 'paperShL',
                    margin: '0 5 0 0',
                    hideLabel: true,
                    bind: {
                        value: '{prevFileVersion.paperShL}',
                        boxLabel: '{glyphPaperShL} Бумажная копия экземпляра Ш актуализирована'
                    }
                },
                {
                    xtype: 'button',
                    glyph: 'xf0c7@FontAwesome',
                    tooltip: 'Сохранить',
                    bind: {
                        hidden: '{isSavePaperBtnHidden}'
                    },
                    listeners: {
                        click: 'onSavePaperShLBtnClick'
                    }
                }
            ]
        },
        {
            xtype: 'fieldcontainer',
            anchor: '100%',
            layout: 'hbox',
            fieldLabel: 'Бумага',
            bind: {
                hidden: '{current.user.positionId !== 9}'
            },
            items: [
                {
                    xtype: 'checkboxfield',
                    reference: 'paperShChTD',
                    margin: '0 5 0 0',
                    hideLabel: true,
                    bind: {
                        value: '{prevFileVersion.paperShChTD}',
                        boxLabel: '{glyphPaperShChTD} Бумажная копия экземпляра дистанции актуализирована'
                    }
                },
                {
                    xtype: 'button',
                    glyph: 'xf0c7@FontAwesome',
                    tooltip: 'Сохранить',
                    bind: {
                        hidden: '{isSavePaperBtnHidden}'
                    },
                    listeners: {
                        click: 'onSavePaperShChTDBtnClick'
                    }
                }
            ]
        },
        {
            xtype: 'displayfield',
            anchor: '100%',
            fieldLabel: 'Чертёж',
            bind: {
                value: '{current.doc.num} {current.doc.descr}'
            }
        },
        {
            xtype: 'displayfield',
            anchor: '33%',
            fieldLabel: 'Дата создания',
            bind: {
                value: '{prevFileVersion.createdDate}'
            }
        },
        {
            xtype: 'displayfield',
            anchor: '33%',
            fieldLabel: 'Предыдущая версия',
            bind: {
                hidden: '{isPrevVersionBtnHidden}',
                value: '{prevFileVersion.prevVersionId}'
            }
        },
        {
            xtype: 'displayfield',
            anchor: '33%',
            fieldLabel: 'Следующая версия',
            bind: {
                hidden: '{isNextVersionBtnHidden}',
                value: '{prevFileVersion.nextVersionId}'
            }
        },
        {
            xtype: 'displayfield',
            anchor: '100%',
            fieldLabel: 'Маршрут',
            bind: {
                value: '{prevFileVersion.routeName}'
            }
        },
        {
            xtype: 'displayfield',
            anchor: '100%',
            fieldLabel: 'Индивидуальный номер',
            bind: {
                value: '{prevFileVersion.id} &nbsp;&nbsp;&nbsp;[{prevFileVersion.branchTypeText}]'
            }
        },
        {
            xtype: 'displayfield',
            anchor: '100%',
            fieldLabel: '№ Листа',
            bind: {
                value: '{prevFileVersion.listNum}'
            }
        },
        {
            xtype: 'displayfield',
            anchor: '100%',
            fieldLabel: 'Hаименование',
            bind: {
                value: '{prevFileVersion.descr}'
            }
        },
        {
            xtype: 'displayfield',
            anchor: '100%',
            fieldLabel: 'Статус',
            bind: {
                value: '{prevFileVersion.statusText}'
            }
        },
        {
            xtype: 'displayfield',
            anchor: '100%',
            cls: 'rejected01',
            fieldLabel: 'Причина отклонения',
            bind: {
                hidden: '{prevFileVersion.rejectMsg == null}',
                value: '{prevFileVersion.rejectMsg}'
            }
        },
        {
            xtype: 'displayfield',
            anchor: '100%',
            fieldLabel: 'Файл',
            bind: {
                value: '{prevFileVersion.name} [{prevFileVersion.kbSize} KB]'
            }
        },
        {
            xtype: 'fieldcontainer',
            anchor: '100%',
            fieldLabel: 'Подлинник проверен',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            bind: {
                hidden: '{isOriginalCheckedHidden}'
            },
            items: [
                {
                    xtype: 'fieldcontainer',
                    flex: 1,
                    defaults: {
                        margin: '0 20 0 0',
                        labelWidth: 50
                    },
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'Должность',
                            labelWidth: 80,
                            value: 'ШЦ (ШТех)'
                        },
                        {
                            xtype: 'textfield',
                            reference: 'fioSign1',
                            fieldLabel: 'ФИО',
                            allowBlank: false,
                            bind: {
                                value: '{prevFileVersion.fioSign1}'
                            }
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'Статус',
                            value: 'Согласовал'
                        },
                        {
                            xtype: 'datefield',
                            reference: 'dateSign1',
                            fieldLabel: 'Дата',
                            bind: {
                                value: '{prevFileVersion.dateSign1}'
                            }
                        }
                    ]
                },
                {
                    xtype: 'fieldcontainer',
                    flex: 1,
                    defaults: {
                        margin: '0 20 0 0',
                        labelWidth: 50
                    },
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'Должность',
                            labelWidth: 80,
                            value: 'руководство Ш'
                        },
                        {
                            xtype: 'textfield',
                            reference: 'fioSign2',
                            fieldLabel: 'ФИО',
                            allowBlank: false,
                            bind: {
                                value: '{prevFileVersion.fioSign2}'
                            }
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'Статус',
                            value: 'Утвердил'
                        },
                        {
                            xtype: 'datefield',
                            reference: 'dateSign2',
                            fieldLabel: 'Дата',
                            bind: {
                                value: '{prevFileVersion.dateSign2}'
                            }
                        },
                        {
                            xtype: 'button',
                            glyph: 'xf0c7@FontAwesome',
                            tooltip: 'Сохранить',
                            bind: {
                                hidden: '{isSaveOriginalCheckedBtnHidden}'
                            },
                            listeners: {
                                click: 'onSaveOriginalCheckedBtnClick'
                            }
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'fieldcontainer',
            anchor: '100%',
            layout: 'hbox',
            fieldLabel: 'Тема',
            items: [
                {
                    xtype: 'textareafield',
                    reference: 'themeShchtd',
                    margin: '0 5 0 0',
                    width: 300,
                    hideLabel: true,
                    bind: {
                        value: '{prevFileVersion.themeShchtd}'
                    }
                },
                {
                    xtype: 'button',
                    glyph: 'xf0c7@FontAwesome',
                    tooltip: 'Сохранить',
                    bind: {
                        hidden: '{isSaveThemeBtnHidden}'
                    },
                    listeners: {
                        click: 'onSaveThemeBtnClick'
                    }
                }
            ]
        },
        {
            xtype: 'fieldcontainer',
            anchor: '100%',
            layout: 'hbox',
            fieldLabel: 'Комментарий',
            bind: {
                hidden: '{isNoteHidden}'
            },
            items: [
                {
                    xtype: 'textareafield',
                    reference: 'noteShl',
                    margin: '0 5 0 0',
                    width: 300,
                    hideLabel: true,
                    bind: {
                        value: '{prevFileVersion.noteShl}'
                    }
                },
                {
                    xtype: 'button',
                    glyph: 'xf0c7@FontAwesome',
                    tooltip: 'Сохранить',
                    bind: {
                        hidden: '{isSaveNoteBtnHidden}'
                    },
                    listeners: {
                        click: 'onSaveNoteBtnClick'
                    }
                }
            ]
        },
        {
            xtype: 'button',
            glyph: 'xf040@FontAwesome',
            text: 'Подписи',
            listeners: {
                click: 'onViewEcpPersonsBtnClick'
            }
        },
        {
            xtype: 'component',
            cls: 'embed01',
            bind: {
                html: '{getEmbedFileHtml}'
            }
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            overflowHandler: 'scroller',
            items: [
                {
                    xtype: 'button',
                    glyph: 'xf060@FontAwesome',
                    text: 'Назад',
                    listeners: {
                        click: 'onBackToFilesBtnClick'
                    }
                },
                {
                    xtype: 'button',
                    glyph: 'xf063@FontAwesome',
                    text: 'Предыдущая',
                    bind: {
                        disabled: '{isPrevVersionBtnHidden}'
                    },
                    listeners: {
                        click: 'onPrevVersionBtnClick'
                    }
                },
                {
                    xtype: 'button',
                    glyph: 'xf062@FontAwesome',
                    text: 'Следующая',
                    bind: {
                        disabled: '{isNextVersionBtnHidden}'
                    },
                    listeners: {
                        click: 'onNextVersionBtnClick'
                    }
                },
                {
                    xtype: 'button',
                    glyph: 'xf093@FontAwesome',
                    text: 'Новая версия',
                    bind: {
                        hidden: '{isNewVersionBtnHidden}'
                    },
                    listeners: {
                        click: 'onNewVersionBtnClick'
                    }
                },
                {
                    xtype: 'button',
                    glyph: 'xf06e@FontAwesome',
                    text: 'Просмотреть',
                    listeners: {
                        click: 'onViewBtnClick'
                    }
                },
                {
                    xtype: 'button',
                    glyph: 'xf019@FontAwesome',
                    text: 'Выгрузить',
                    listeners: {
                        click: 'onDownloadBtnClick'
                    }
                },
                {
                    xtype: 'button',
                    glyph: 'xf040@FontAwesome',
                    text: 'Подписать',
                    bind: {
                        disabled: '{isSignBtnDisabled}',
                        hidden: '{isSignBtnHidden}'
                    },
                    listeners: {
                        click: 'onSignBtnClick'
                    }
                },
                {
                    xtype: 'button',
                    glyph: 'xf05e@FontAwesome',
                    text: 'Отклонить',
                    bind: {
                        hidden: '{isRejectBtnHidden}'
                    },
                    listeners: {
                        click: 'onRejectBtnClick'
                    }
                },
                {
                    xtype: 'button',
                    glyph: 'xf0e2@FontAwesome',
                    text: 'Отменить отклонение',
                    bind: {
                        hidden: '{isRejectCancelBtnHidden}'
                    },
                    listeners: {
                        click: 'onRejectCancelBtnClick'
                    }
                }
            ]
        }
    ]

});