/*
 * File: app/view/file/FileListViewModel.js
 *
 * This file was generated by Sencha Architect version 4.2.8.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.view.file.FileListViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.file.filelistview',

    requires: [
        'Ext.data.Store',
        'Ext.app.bind.Formula'
    ],

    stores: {
        fileStore: {
            remoteFilter: true,
            remoteSort: true,
            model: 'ASTD.model.FileModel'
        }
    },
    formulas: {
        isUploadBtnHidden: function(get) {
            var isHidden = false;
            var user = this.get('current.user');
            if(!user) {
                return true;
            }
            isHidden = user.get('positionId') !== 9 && user.get('positionId') !== 5;
            return isHidden;
        },
        isCompareBtnHidden: function(get) {
            var file = get('current.file');
            var user = this.get('current.user');
            if(!file || !user) {
                return true;
            }


            return !file.get('canBeCompared');
        },
        isChangeRouteBtnHidden: function(get) {
            var file = get('current.file');
            var user = this.get('current.user');
            if(!file || !user) {
                return true;
            }


            return false;
        },
        isDeleteBtnHidden: function(get) {
            var file = get('current.file');
            var user = this.get('current.user');
            if(!file || !user) {
                return true;
            }

            if(file.get('hasNextVersion')) {
                return true;
            }

            if(
            (user.get('positionId') === 5 && file.get('status') === 'REJECTED') ||
            (user.get('positionId') === 9 && file.get('routePositionId') === 9 &&
            (file.get('status') === 'DEFAULT' || file.get('status') === 'SIGNING' && file.get('signedNum') <= 2)) ||
            (user.get('positionId') === 5 && file.get('routePositionId') === 5 && file.get('status') === 'DEFAULT' )
            ) {
                return false;
            }

            return true;
        },
        isArchiveBtnHidden: function(get) {
            var isHidden = false;

            var file = get('current.file');
            var user = this.get('current.user');
            if(!file || !user) {
                return true;
            }

            var branchType = this.get("current.branchType");

            isHidden = branchType === 'ARCHIVE' || user.get('positionId') !== 5 || file.get('signedNum') === 0;

            return isHidden;
        },
        isEditBtnHidden: function(get) {
            var isHidden = false;
            var catalog = get('current.catalog');
            var user = this.get('current.user');
            if(!catalog || !user) {
                return true;
            }
            isHidden = catalog.get('branchType') === 'REJECTED' || catalog.get('branchType') === 'ARCHIVE' ||
            (user.get('positionId') !== 9 && user.get('positionId') !== 5);

            if(!isHidden) {
                var file = get('current.file');
                if(!file) {
                    return isHidden;
                }
                isHidden = file.get('status') === 'APPROVED' || file.get('status') === 'REFERENCE' || file.get('status') === 'DAMAGED' || file.get('status') === 'INVALID' ||
                file.get('status') === 'SIGNING' || file.get('status') === 'REJECTED';

                if(!isHidden){
                    isHidden =  file.get('routePositionId') !== user.get('positionId');
                }
            }

            return isHidden;
        },
        breadCrumbs: function(get) {
            var catalog = get('current.catalog');
            if(!catalog || !catalog.parentNode || !catalog.parentNode.parentNode) {
                return '';
            }
            var tcatalog = catalog.parentNode.parentNode.data.name + ' > ' + catalog.parentNode.data.name + ' > ' +
            catalog.data.name  + ' > ';
            var doc = get('current.doc');
            if(!doc) {
                return tcatalog;
            }
            return tcatalog + '<span>' + doc.data.num + '&nbsp;&nbsp;&nbsp;' + doc.data.descr  + ' ></span> ';
        },
        isArchiveCancelBtnHidden: function(get) {
            var isHidden = false;
            var file = get('current.file');
            var user = this.get('current.user');
            if(!file || !user) {
                return true;
            }

            isHidden = file.get('branchType') !== 'ARCHIVE' || user.get('positionId') !== 5 || file.get('hasNextVersion');

            return isHidden;
        },
        isSignedReviewColumnHidden: function(get) {
            var branchType = get('current.branchType');
            var user = this.get('current.user');
            if(!branchType || !user) {
                return true;
            }
            return branchType !== 'APPROVED';
        }
    }

});