/*
 * File: app/view/file/FileRejectFormViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.view.file.FileRejectFormViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.file.filerejectformview',

    id: 'fileRejectFormViewController',

    onComplete: function(options, success, response) {
                Ext.Msg.hide();
                Ext.toast({
                    title: 'Отклонение',
                    html: success ? 'Данные успешно сохранены' : 'Ошибка',
                    align: 'tr',
                    bodyPadding: 10
                });
                // Ext.Msg.wait("Загрузка", "Загрузка формы");
                // this.getViewModel().get('fileList').getStore().reload();
                this.fireEvent('clickFileHistoryBtn', this.getViewModel().get('fileHistoryForm'),
                    this.getViewModel().get('currentFile'),
                    this.getViewModel().get('currentFile').get('id'));
                this.getView().close();
    },

    onSaveClick: function(button, e, eOpts) {
        var form = this.lookupReference('docRejectForm');

        if (form.isValid()) {
            Ext.Msg.wait('Сохранение', 'Сохранение данных...');

            var currentFile = this.getViewModel().get('currentFile');
            Ext.Ajax.request({
                url: currentFile.getProxy().getUrl() + '/reject/' + currentFile.getId(),
                method: 'POST',
                params: {msg: this.getViewModel().get('msg')},
                scope: this,
                callback: this.onComplete
            });
        }
    },

    onCancelClick: function(button, e, eOpts) {
        this.getView().close();
    }

});
