/*
 * File: app/view/catalog/CatalogListViewModel.js
 *
 * This file was generated by Sencha Architect version 4.2.8.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.view.catalog.CatalogListViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.catalog.cataloglistview',

    requires: [
        'Ext.data.TreeStore',
        'Ext.app.bind.Formula'
    ],

    stores: {
        catalogStore: {
            type: 'tree',
            remoteFilter: true,
            autoLoad: true,
            model: 'ASTD.model.CatalogModel',
            listeners: {
                beforeload: 'onCatalogStoreBeforeLoad',
                load: 'onCatalogStoreLoad'
            }
        }
    },
    formulas: {
        isCreateBtnHidden: function(get) {
            var catalog = get('current.catalog');
            var user = this.get('current.user');
            if(!catalog || !user || !catalog.get('isCatalog')) {
                return true;
            }
            return catalog.get('type') === 'SCHEME' || catalog.get('type') === 'ROOT' ||
            (user.get('positionId') !== 5 && user.get('positionId') !== 9);
        },
        isEditBtnHidden: function(get) {
            var catalog = get('current.catalog');
            var user = this.get('current.user');
            if(!catalog || !user || !catalog.get('isCatalog')) {
                return true;
            }
            return catalog.get('type') === 'ROOT' || catalog.get('type') === 'STATION' || catalog.get('type') === 'LINE' ||
            (user.get('positionId') !== 5 && user.get('positionId') !== 9);
        },
        isDeleteBtnHidden: {
            get: function(data) {
                // var catalog = data('current.catalog');
                var catalog = data;
                var user = this.get('current.user');
                if(!catalog || !user || !catalog.get('isCatalog')) {
                    return true;
                }
                return catalog.get('type') === 'ROOT' || catalog.get('type') === 'STATION' || catalog.get('type') === 'LINE' ||
                catalog.get('readOnly') ||
                (user.get('positionId') !== 5 && user.get('positionId') !== 9);
            },
            bind: {
                bindTo: '{current.catalog}',
                deep: true
            }
        }
    }

});