/*
 * File: app/view/catalog/CatalogListViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.8.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.view.catalog.CatalogListViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.catalog.cataloglistview',

    onCompleteDelete: function(record, operation, success) {
        Ext.Msg.hide();
        if(success){
            this.fireViewEvent('clickCatalogList', this.getView(), this.getView().getSelection()[0].parentNode);
            record.remove();

            var parentCatalog = this.getView().getSelection()[0];
            if(!parentCatalog.hasChildNodes()){
                this.getViewModel().get('current.catalog').set('readOnly', false);
            }

            var records = operation.getResultSet().getRecords();
          //  var virtualCatalogs = ASTD.Utils.getVirtualCatalogs(records, 1);
            var rootCatalog = ASTD.Utils.getParentCatalog(parentCatalog, 0);
           /* for(var i = 0; i < virtualCatalogs.length; i++){
                var virtualCatalog = rootCatalog.findChildBy(function(node){
                    return node.get('branchType') === virtualCatalogs[i].get('branchType') &&
                        node.get('realId') === virtualCatalogs[i].get('realId');
                }, this, true);
                virtualCatalog.remove();
            }*/
        } else {
            record.dropped = false;
        }
        Ext.toast({
            title: 'Удаление',
            html: success ? 'Каталог успешно удален' : 'Ошибка',
            align: 'tr',
            bodyPadding: 10
        });
    },

    addMenuItems: function(rootNode) {
        if(this.getViewModel().get('current.user') && this.getViewModel().get('current.user').get('positionId') === 5) {
            rootNode.appendChild({text:'Пользователи', iconCls: 'x-fa fa-users',  leaf:true, id:'user', isCatalog:false}, true);
        }
        rootNode.appendChild({text:'Журнал аудита', iconCls: 'x-fa fa-book', leaf:true, id:'audit', isCatalog:false}, true);
    },

    onTreepanelItemClick: function(dataview, record, item, index, e, eOpts) {
        this.fireViewEvent('clickCatalogList', this.getView(), record);
    },

    onCreateCatalogBtnClick: function(button, e, eOpts) {
        //this.onCreateBtnClick(false);
        if(!ASTD.Utils.isSelected(this.getView().getSelection()[0])){
            return false;
        }
        var parentCatalog = this.getView().getSelection()[0];

        var level = parentCatalog.get('level') + 1;
        var win = new ASTD.view.catalog.CatalogFormView({
            viewModel: {
                data: {
                    currentCatalog: Ext.create('ASTD.model.CatalogModel', {
                        parentCatalogId: parentCatalog.getId(),
                        level: level,
                        type: level > 1 ? 'SCHEME' : 'DEFAULT'

                    }),
                    parentCatalog: parentCatalog
                }
            }
        });

        win.show();
    },

    onEditBtnClick: function(button, e, eOpts) {
        if(!ASTD.Utils.isSelected(this.getView().getSelection()[0])){
            return false;
        }
        var win = new ASTD.view.catalog.CatalogFormView({
            viewModel: {
                data: {
                    currentCatalog: this.getView().getSelection()[0],
                    parentCatalog: this.getView().getSelection()[0].parentNode
                }
            }
        });

        win.show();
    },

    onDeleteBtnClick: function(button, e, eOpts) {
        if(!ASTD.Utils.isSelected(this.getView().getSelection()[0])){
            return false;
        }
        Ext.Msg.show({
            title:'Удалить?',
            message: 'Вы действительно хотите удалить?',
            buttons: Ext.Msg.YESNO,
            icon: Ext.Msg.QUESTION,
            scope: this,
            fn: function(btn) {
                if(btn === 'yes') {
                    var currentCatalog = this.getView().getSelection()[0];
                    Ext.Msg.wait('Удаление', 'Удаление каталога...');
                    currentCatalog.dropped = true;
                    currentCatalog.save({
                        scope: this,
                        callback: this.onCompleteDelete
                    });
                }
            }
        });
    },

    onCatalogStoreBeforeLoad: function(store, operation, eOpts) {
        this.fireViewEvent('loadCurrentUserInfo', this.getView());
        Ext.Msg.wait("Загрузка", "Загрузка списка");
    },

    onCatalogStoreLoad: function(treestore, records, successful, operation, node, eOpts) {
        if(successful){
            this.addMenuItems(node);
        }

    }

});
