/*
 * File: app/view/catalog/CatalogFormView.js
 *
 * This file was generated by Sencha Architect version 4.2.8.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.view.catalog.CatalogFormView', {
    extend: 'Ext.window.Window',
    alias: 'widget.catalog.catalogformview',

    requires: [
        'ASTD.view.catalog.CatalogFormViewModel',
        'ASTD.view.catalog.CatalogFormViewController',
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    controller: 'catalog.catalogformview',
    viewModel: {
        type: 'catalog.catalogformview'
    },
    modal: true,
    width: 350,
    layout: 'fit',
    header: {
        iconCls: 'x-fa fa-edit'
    },
    title: 'Каталог',

    items: [
        {
            xtype: 'form',
            reference: 'catalogForm',
            modelValidation: true,
            bodyPadding: 10,
            header: false,
            items: [
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Наименование',
                    bind: {
                        value: '{currentCatalog.name}'
                    }
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    ui: 'footer',
                    layout: {
                        type: 'hbox',
                        pack: 'end'
                    },
                    items: [
                        {
                            xtype: 'button',
                            iconCls: 'x-fa fa-save',
                            text: 'Сохранить',
                            listeners: {
                                click: 'onSaveClick'
                            }
                        },
                        {
                            xtype: 'button',
                            iconCls: 'x-fa fa-times',
                            text: 'Отменить',
                            listeners: {
                                click: 'onCancelClick'
                            }
                        }
                    ]
                }
            ]
        }
    ]

});