/*
 * File: app/view/catalog/CatalogFormViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.view.catalog.CatalogFormViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.catalog.catalogformview',

    onComplete: function(record, operation, success) {
        Ext.Msg.hide();
        if(success){
            var records = operation.getResultSet().getRecords();
          //  var virtualCatalogs = ASTD.Utils.getVirtualCatalogs(records, 1);
            var rootCatalog = ASTD.Utils.getParentCatalog(this.getViewModel().get('parentCatalog'), 0);

            switch(operation.getRequest().getMethod()){
              /*  case 'PUT':
                    for(var i = 0; i < virtualCatalogs.length; i++){
                        var virtualCatalog = rootCatalog.findChildBy(function(node){
                            return node.get('branchType') === virtualCatalogs[i].get('branchType') &&
                                node.get('realId') === virtualCatalogs[i].get('realId');
                        }, this, true);
                        virtualCatalog.set('text', virtualCatalogs[i].get('name'));
                        virtualCatalog.set('name', virtualCatalogs[i].get('name'));
                    }
                    break;*/
                case 'POST':
                    this.getViewModel().get('parentCatalog').appendChild(record);
                    if(!this.getViewModel().get('parentCatalog').get('readOnly')){
                        this.getViewModel().get('parentCatalog').set('readOnly', true);
                    }
                    this.getViewModel().get('parentCatalog').sort(
                        function(node1, node2) {
                            return node1.getId() - node2.getId();
                        }
                    );

                   /* for(var i = 0; i < virtualCatalogs.length; i++){
                        var parentVirtualCatalog = rootCatalog.findChildBy(function(node){
                            return node.get('branchType') === virtualCatalogs[i].get('branchType') &&
                                node.get('realId') === this.getViewModel().get('parentCatalog').get('realId');
                        }, this, true);
                        parentVirtualCatalog.appendChild(virtualCatalogs[i]);
                    }*/

                    break;
            }

            this.getView().close();

        }
        Ext.toast({
            title: 'Сохранение',
            html: success ? 'Каталог успешно сохранен' : 'Ошибка',
            align: 'tr',
            bodyPadding: 10
        });

    },

    onSaveClick: function(button, e, eOpts) {
        var form = this.lookupReference('catalogForm'),
            rec;

        if (form.isValid()) {
            rec = this.getViewModel().get('currentCatalog');
            Ext.Msg.wait('Сохранение', 'Сохранение каталога...');
            rec.save({
                scope: this,
                callback: this.onComplete
            });
        }
    },

    onCancelClick: function(button, e, eOpts) {
        this.getViewModel().get('currentCatalog').reject();
        this.getView().close();
    }

});
