/*
 * File: app/view/catalog/CatalogListView.js
 *
 * This file was generated by Sencha Architect version 4.2.8.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ASTD.view.catalog.CatalogListView', {
    extend: 'Ext.tree.Panel',
    alias: 'widget.catalog.cataloglistview',

    requires: [
        'ASTD.view.catalog.CatalogListViewModel',
        'ASTD.view.catalog.CatalogListViewController',
        'Ext.tree.View',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    controller: 'catalog.cataloglistview',
    viewModel: {
        type: 'catalog.cataloglistview'
    },
    width: 250,
    collapsible: true,
    header: {
        iconCls: 'x-fa fa-folder-open'
    },
    title: 'Меню',
    split: true,
    rootVisible: false,

    bind: {
        selection: '{current.catalog}',
        store: '{catalogStore}'
    },
    listeners: {
        itemclick: 'onTreepanelItemClick'
    },
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            height: 45,
            items: [
                {
                    xtype: 'component',
                    html: 'Каталоги:'
                },
                {
                    xtype: 'button',
                    iconCls: 'x-fa fa-plus',
                    tooltip: 'Создать',
                    bind: {
                        hidden: '{isCreateBtnHidden}'
                    },
                    listeners: {
                        click: 'onCreateCatalogBtnClick'
                    }
                },
                {
                    xtype: 'button',
                    iconCls: 'x-fa fa-edit',
                    tooltip: 'Редактировать',
                    bind: {
                        hidden: '{isEditBtnHidden}'
                    },
                    listeners: {
                        click: 'onEditBtnClick'
                    }
                },
                {
                    xtype: 'button',
                    iconCls: 'x-fa fa-minus',
                    tooltip: 'Удалить',
                    bind: {
                        hidden: '{isDeleteBtnHidden}'
                    },
                    listeners: {
                        click: 'onDeleteBtnClick'
                    }
                }
            ]
        }
    ]

});